### ISSUE TITLE
Feature request: Vary on headers

### ISSUE THREAD

**Issue by jleclanche** [reclosedev/requests-cache#101]
Requests Cache is amazing when prototyping with foreign APIs :)

One thing missing seems to be the ability to vary on request headers. For example:

```py
import requests_cache; requests_cache.install_cache("example", vary_headers=("Accept",))

requests.get("https://api.example.com", headers={"accept": "application/json"})
requests.get("https://api.example.com", headers={"accept": "application/xml"})
```

This would add the `accept` header part of the cache key, which would make it possible to cache the same page multiple times depending on the header passed to requests.

WDYT?

**Comment by soundstripe** [comment]
I certainly think this would be useful. Some APIs are designed to take optional parameters in their headings. Having to clear the cache to make this type of request makes this package less useful for those APIs.

I'm wondering if the author has taken a hiatus from this project though. We might have to fork to get this feature.

**Comment by JWCook** [comment]
Well, it's a couple years later now, but both of these things have happened. requests-cache is now being maintained via Code Shelter, and there is now a parameter that includes headers when creating cache keys:
```python
session = CachedSession(include_get_headers=True)
```
