### ISSUE TITLE
Feature Request: A way to set expire_after on a per URL basis.

### ISSUE THREAD

**Issue by vulcan25** [reclosedev/requests-cache#108]
As per the docs I am currently doing this...

    import requests_cache
    requests_cache.install_cache('my_cache', backend='sqlite', expire_after=120)

However my application queries a number of different APIs which each have their own rate limits.  It would be great if I could then do something like:

    url = 'https://example.com/api/endpoint'
    requests_cache.set_expiry(url, 15)

**Comment by shoeffner** [comment]
I would also love this have this feature and would even like to expand it to matchers, as the base URL for APIs usually stays the same, e.g. something like
```python
requests_cache.set_expiry('.+/endpoint', 15)
```
or with similar regex support. However, a first step towards that directory is using a custom `session_factory`.

```python
import requests_cache
from datetime import timedelta

# A normal dictionary might be sufficient,
# but I wanted to handle the timedelta conversion transparently
class RequestRegistry(dict):
    def __getitem__(self, key):
        try:
            return super().__getitem__(key)
        except KeyError:
            return 'default'

    def __setitem__(self, key, value):
        if value is not None:
            value = value if isinstance(value, timedelta) else timedelta(seconds=value)
        super().__setitem__(key, value)

request_registry = RequestRegistry()

def register_url(url, expire_after):
    request_registry[url] = expire_after

class PerURLCacheSession(requests_cache.CachedSession):
    def send(self, request, **kwargs):
        expire_after = request_registry[request.url]
        # Let's keep this print for now for the output below, but you can remove it
        print(request.url, expire_after)
        if expire_after == 'default':
            return super().send(request, **kwargs)

        old, self._cache_expire_after = self._cache_expire_after, expire_after
        try:
            return super().send(request, **kwargs)
        finally:
            self._cache_expire_after = old

# To expose the API you used above
requests_cache.set_expiry = register_url
```

To test it, I used the following snippet where you can see how to register your own `session_factory`:
```python
if __name__ == '__main__':
    import time
    import requests

    requests_cache.install_cache(backend='memory', session_factory=PerURLCacheSession)

    def test_url(expiry):
        url = 'https://httpbin.org/get'

        # set expiry
        requests_cache.set_expiry(url, expiry)
        for i in range(2):
            resp = requests.get(url)
            print(url, 'From cache:', resp.from_cache)
        print('sleep...')
        time.sleep(1)
        for i in range(2):
            resp = requests.get(url)
            print(url, 'From cache:', resp.from_cache)

    print('Expire after 1 second:')
    test_url(1)
    print('No expiration:')
    test_url(None)
    print('Always expire:')
    test_url(-1)
```
Output:
```
Expire after 1 second:
https://httpbin.org/get 0:00:01
https://httpbin.org/get From cache: False
https://httpbin.org/get 0:00:01
https://httpbin.org/get From cache: True
sleep...
https://httpbin.org/get 0:00:01
https://httpbin.org/get From cache: False
https://httpbin.org/get 0:00:01
https://httpbin.org/get From cache: True
No expiration:
https://httpbin.org/get None
https://httpbin.org/get From cache: True
https://httpbin.org/get None
https://httpbin.org/get From cache: True
sleep...
https://httpbin.org/get None
https://httpbin.org/get From cache: True
https://httpbin.org/get None
https://httpbin.org/get From cache: True
Always expire:
https://httpbin.org/get -1 day, 23:59:59
https://httpbin.org/get From cache: False
https://httpbin.org/get -1 day, 23:59:59
https://httpbin.org/get From cache: False
sleep...
https://httpbin.org/get -1 day, 23:59:59
https://httpbin.org/get From cache: False
https://httpbin.org/get -1 day, 23:59:59
https://httpbin.org/get From cache: False
```

This shows that it mostly works as expected, but there's one minor caveat: Since it's easy to overwrite expiry times, the "No expiration" block already uses the value stored inside the cache. But this might or might not be the correct behaviour, for my use case it's sufficient as caching per endpoint does not change. Another caveat is that in this simple example the expirations are only stored in memory, not alongside the database entries which might be a useful addition. Also note that this code is not thread-safe, as the setting/resetting of `self._cache_expire_after` is subject to race conditions.

It is definitely not the best solution but at least it solves this problem for me (for now).

P.S.: Depending on your use case it might also be needed to implement the [requests_cache.CachedSession.request](https://github.com/reclosedev/requests-cache/blob/master/requests_cache/core.py#L121-L136) method, but for me this didn't cause any troubles yet...

**Comment by shoeffner** [comment]
I revisited my solution from yesterday and noticed some other problems. While resolving them, I came up with this little module: https://github.com/shoeffner/requests-url-cache . You can try it out like this:

```python
import requests
import requests_cache

from requests_url_cache import PerURLCacheSession, register_url

requests_cache.install_cache('test', backend='sqlite', session_factory=PerURLCacheSession)

# Usage e.g.
register_url('https://httpbin.org/anything', 20)
requests.get('https://httpbin.org/get', expire_after=10)
```

It's not on pypi, but you can install it from github:

```bash
pipenv install -e git+https://github.com/shoeffner/requests-url-cache#egg=requests-url-cache
# or
pip install -e git+https://github.com/shoeffner/requests-url-cache#egg=requests-url-cache
```

**Comment by vulcan25** [comment]
Nice response!  This has helped me out.

**Comment by payne92** [comment]
This feature would be helpful.

Perhaps a simple context manager would work, in the same style as `requests_cache.disabled()`:

```
with requests_cache.expire_after(5*60*60):
    print(requests.get('http://httpbin.org/ip').text)
```

**Comment by shoeffner** [comment]
This is possible using the solution I added above:

```python
import requests, requests_cache
from requests_url_cache import PerURLCacheSession

with requests_cache.enabled(session_factory=PerURLCacheSession, expire_after=5*60*60):
    response = requests.get('http://httpbin.org/ip')
```

Note however, that this persists across contexts – but maybe that's what you want:

```python
import requests, requests_cache
from requests_url_cache import PerURLCacheSession

with requests_cache.enabled(session_factory=PerURLCacheSession, expire_after=5*60*60):
    response = requests.get('http://httpbin.org/ip')
    print(response.from_cache)  # False

response = requests.get('http://httpbin.org/ip')
print(hasattr(response, 'from_cache'))  # False (no cache used)

with requests_cache.enabled(session_factory=PerURLCacheSession, expire_after=5*60*60):
    response = requests.get('http://httpbin.org/ip')
    print(response.from_cache)  # True
```

If you definitely want to have the `expire_after` syntax, you can monkey-patch requests_cache:

```python
from contextlib import contextmanager

import requests, requests_cache
from requests_url_cache import PerURLCacheSession

@contextmanager
def expiry_ctx_manager(t='default'):
    with requests_cache.enabled(session_factory=PerURLCacheSession, expire_after=t):
        yield
requests_cache.expire_after = expiry_ctx_manager

with requests_cache.expire_after(5 * 60 * 60):
    print(requests.get('http://httpbin.org/ip').text)
```

**Comment by JWCook** [comment]
I would find this useful as well, and there are a couple other issues requesting different variations of this.

Would anyone be interested in putting together a PR to merge @shoeffner's changes (or something similar) into requests-cache?

**Comment by shoeffner** [comment]
It's nice that the project got picked up again! And don't ask me why I did not make PR back then but wrote my own module (I even state in the README that if a solution is built into requests-cache, the module would no longer be needed)...

Maybe I can spend some time next weekend to see how to incorporate the changes – but I am definitely also happy with someone else doing it.

**Comment by JWCook** [comment]
With PR #177, I'll consider this issue done since per-request expiration can be used to accomplish per-URL expiration.

To expand on this and make the per-URL case easier, I made issue #184 as a follow-up to this.
