### ISSUE TITLE
Add support for caching multipart file uploads

### ISSUE THREAD

**Issue by gregdingle** [reclosedev/requests-cache#113]
First, thanks for the great library! I'm using it extensively in my current project.

After some debugging, I found that requests-cache does not cache requests that have the `files` param set, because the form field boundary in the request body is randomized. See http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file . 

After some research, I found that the recommended way to customize the boundary with `requests` is using requests-toolbelt. See https://toolbelt.readthedocs.io/en/latest/uploading-data.html#streaming-multipart-data-encoder . 

However, this was not working with my target form for unknown reasons, so I settled on a more direct fix: monkey-patching the underlying `urllib3.filepost.choose_boundary` to return a constant value. 

```
urllib3.filepost.choose_boundary = lambda: 'my_super_special_form_boundary'
```

This could be made an option of `requests_cache.install_cache`. At least, it would be good to note the cache key limitation in the docs. 

Also, `ignore_params` does not work at all with a `multipart/form-data` request.

**Comment by JWCook** [comment]
@gregdingle I see that this issue is a couple years old now, but are you still using requests-cache, and is support for multipart form data something you're still interested in?

**Comment by gregdingle** [comment]
I'm not interested anymore but the software I wrote lives on with the workaround I implemented. 

--
Greg Dingle

**Comment by gregdingle** [comment]
I'm not interested anymore but the software I wrote lives on with the workaround I implemented. 

--
Greg Dingle

**Comment by JWCook** [comment]
Frustratingly, requests uses `urllib3.request.encode_multipart_formdata()`, which does accept a custom boundary, but requests doesn't support passing any keyword args to it ([here](https://github.com/psf/requests/blob/c45a4dfe6bfc6017d4ea7e9f051d6cc30972b310/requests/models.py#L169)).

After doing a bit more digging on this, I couldn't find a better solution than the one you posted, so I ended up using that. It will only be used if `allowable_methods` includes POST and if `files` are specified.

Thanks for the tip!
