### ISSUE TITLE
cache does not seem to work for lower level request object

### ISSUE THREAD

**Issue by olymk2** [reclosedev/requests-cache#114]
Using requests Session() onject and Request() object seems to by pass the caching.

If I use requests.get it all works fine and gets request however REquest('GET', url) does not appear to call the caching object.

Should this work or is it a bug ?

**Comment by reclosedev** [comment]
You can use CachedSession directly https://requests-cache.readthedocs.io/en/latest/api.html#requests_cache.core.CachedSession

Another option is to call https://requests-cache.readthedocs.io/en/latest/api.html#requests_cache.core.install_cache before import of requests

**Comment by jayvdb** [comment]
> Another option is to call requests-cache.readthedocs.io/en/latest/api.html#requests_cache.core.install_cache before import of requests

The README imports requests before calling `install_cache`.  Maybe that should be changed?  and/or `CachedSession` also mentioned in the README very briefly "For uses other than `requests.get`, it is advisable to use `CachedSession`."

**Comment by JWCook** [comment]
I see this issue is a couple years old now, but both of these problems appear to have already been fixed in the current master branch (not yet released).

@olymk2 To clarify, you're talking about using prepared requests? As in:
```python
import requests
import requests_cache

requests_cache.install_cache()
request = requests.Request('GET', 'https://httpbin.org/get')
session = requests.Session()
response_1 = session.send(request.prepare())
response_2 = session.send(request.prepare())
```

If so, that usage working now. Also, `install_cache()` can be called after importing requests.
