### ISSUE TITLE
Feature Request: use a function to determine whether or not to cache

### ISSUE THREAD

**Issue by AlJohri** [reclosedev/requests-cache#117]
I have a weird API that always returns status code of 200 with bad responses. I want to use a function to return false given a response when the result should not be cached

I currently hacked around it like this:

```python
    r = session.post(url, headers=headers, data=payload)

    # HACK: clear if cached error and repeat request
    if r.from_cache and r.json()['status']['code'] != 0:
        key = session.cache.create_key(r.request)
        session.cache.delete(key)
        r = session.post(url, headers=headers, data=payload)
```

@reclosedev I can submit a PR for this if you're amenable

**Comment by reclosedev** [comment]
I think #104 will work
