### ISSUE TITLE
expose sqlite3 timeout parameter in dbdict?

### ISSUE THREAD

**Issue by backbord** [reclosedev/requests-cache#119]
Hi,

I run requests-cache under some load with large responses being stored in the sqlite cache backend.
Sometimes, the call to `.remove_expired_responses()` takes several seconds and concurrent use of the cache is then brought to a halt with `sqlite3.OperationalError: Database is locked`.

In the code of [DbDict](https://github.com/reclosedev/requests-cache/blob/5fe2bc23ba29c2aeeb55be15458f6443264db3a2/requests_cache/backends/storage/dbdict.py#L62-L79) it seems that [sqlite3.connect()](https://docs.python.org/3.7/library/sqlite3.html#sqlite3.connect) is called w/o an explicit timeout, so that the default value of 5 seconds is used.

Here, I would like to be able to fine-tune the `timeout` for the sqlite backend, perhaps as a parameter to [DbCache](https://github.com/reclosedev/requests-cache/blob/5fe2bc23ba29c2aeeb55be15458f6443264db3a2/requests_cache/backends/sqlite.py#L13-L29), if you agree that this would be something you'd want to expose.

Thanks and best regards,  
Tim

**Comment by JWCook** [comment]
The `timeout` param is now in the current master branch.

**Comment by vucan1892001** [comment]
How can I set the `timeout` parameter infinity?
