### ISSUE TITLE
Get the timestamp of when a HTTP response got cached, from request_cache

### ISSUE THREAD

**Issue by DeqingQu** [reclosedev/requests-cache#120]
Hi,

Is it possible to get the timestamp of when an HTTP response got cached, from request_cache?

We are using request_cache in our project and the cache file is more than 100 GB now. Some of the caches are out of date but we don't know how to identify the expired cache. Is there any idea?

**Comment by DeqingQu** [comment]
I found another python module 'CacheControl' which could satisfy my requirements. It could be an alternative solution as the requests-cache is not updated anymore.
https://cachecontrol.readthedocs.io/en/latest/

We can use the 'Custom Caching Strategy' in CacheControl to implement the time-based cache strategy.
https://cachecontrol.readthedocs.io/en/latest/custom_heuristics.html

**Comment by reclosedev** [comment]
You can remove old entries with https://requests-cache.readthedocs.io/en/latest/api.html#requests_cache.backends.base.BaseCache.remove_old_entries
See https://requests-cache.readthedocs.io/en/latest/user_guide.html#expiration for example

btw, CacheControl is listed in README of this project :)

**Comment by JWCook** [comment]
For reference, as of 0.7 there are now many more options for setting cache expiration, including Cache-Control headers.
