### ISSUE TITLE
Is it possible to query sqlite backend if it has url?

### ISSUE THREAD

**Issue by oppsig** [reclosedev/requests-cache#132]
I install cache like this:
```
import requests_cache
requests_cache.install_cache('name', backend='sqlite', expire_after=3600)
```

Does requests_cache have an api to query sqlite backend if a specific url exists in the cache before I send the request. I know I can check if an response was from cache, but I would like to check before sending response.

**Comment by reclosedev** [comment]
Yes, you can use [has_url](https://requests-cache.readthedocs.io/en/latest/api.html#requests_cache.backends.base.BaseCache.has_url) and [has_key](https://requests-cache.readthedocs.io/en/latest/api.html#requests_cache.backends.base.BaseCache.has_key) methods

Examples from tests
```python
# For GET requests
session.cache.has_url(url)
# For POST requests
req = Request('POST', url).prepare()
session.cache.has_key(session.cache.create_key(req))
```
If you don't have your own session, and cache is installed globally you can get cache objects using ``requests_cache.core.get_cache()``

**Comment by oppsig** [comment]
Ok excellent, will test this 😊
