### ISSUE TITLE
sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type

### ISSUE THREAD

**Issue by lysobrody222** [reclosedev/requests-cache#137]
The problem is probably the size of the file - 1.5 GB.
```python
requests_cache.install_cache(expire_after=timedelta(seconds=3))
requests.get("http://mirrors.evowise.com/linuxmint/stable/18/linuxmint-18-xfce-32bit.iso")
```
Using requests-cache 0.5.0 with Python 3.7.3 on linux mint 19.1
Is it possible to add support for large files?

**Comment by JWCook** [comment]
Unfortunately the filesize limit is a limitation of sqlite, an likely all the other current backends. See #142 for a similar issue. The simplest option for storing large files would be the filesystem backend discussed in issue #30.
