### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mgedmin** [reclosedev/requests-cache#139]
Any chance of a new release on PyPI?  The collections.abc deprecation warnings are bugging me, but I see the fix was already merged to git master (#131).

**Comment by reclosedev** [comment]
Done https://pypi.org/project/requests-cache/0.5.1/

**Comment by mgedmin** [comment]
Welp, I guess the fix in #131 was incomplete:

```
$ tox -re py38
...
py38 installed: ...,requests-cache==0.5.1,...
...
============================================================= warnings summary =============================================================
.tox/py38/lib/python3.8/site-packages/requests_cache/backends/storage/redisdict.py:9
  /home/mg/src/ghcloneall/.tox/py38/lib/python3.8/site-packages/requests_cache/backends/storage/redisdict.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import MutableMapping
```

#131 fixed the warning in the mongodb backend, but a similar fix is needed in the redis backend as well.

(Python displays each warning only once by default, which makes this kind of warning fixing annoying.)

**Comment by mgedmin** [comment]
I've filed #140 for that.

**Comment by mgedmin** [comment]
(I apologize for not actually testing git master before asking for a new release.)

**Comment by reclosedev** [comment]
No problem, thanks for PR. https://pypi.org/project/requests-cache/0.5.2/
