### ISSUE TITLE
sqlite3 cache backend can't store more then 4 GiB

### ISSUE THREAD

**Issue by yelled3** [reclosedev/requests-cache#142]
When using the default sqlite3 backend, i.e `DbCache` and trying to cache a request with raw bytes larger then 4 GiB I get the following error:

```py
    self.__cached_session.cache.save_response(cache_key, response)
  File ".../.venv/lib/python3.7/site-packages/requests_cache/backends/base.py", line 46, in save_response
    self.responses[key] = self.reduce_response(response), datetime.utcnow()
  File ".../.venv/lib/python3.7/site-packages/requests_cache/backends/storage/dbdict.py", line 165, in __setitem__
    sqlite.Binary(pickle.dumps(item)))

OverflowError: cannot serialize a bytes object larger than 4 GiB
```

This seems to be a known limitation of `pickle.dumps()` 

see: 
* https://stackoverflow.com/questions/29704139/pickle-in-python3-doesnt-work-for-large-data-saving
* https://issues.apache.org/jira/browse/SPARK-18161

So from what I see, either we need to split the cache into smaller chunks and re-assemble it when loading it.
Or replace the serializer to something that can handle large amounts of data.

Any suggestions?

**Comment by rafalslaby** [comment]
4 GiB limit on serialization is not the only problem. Currently, the [max BLOB size](https://www.sqlite.org/limits.html) in sqlite database is 2.147483647 GB. [See this](https://github.com/reclosedev/requests-cache/issues/137).

**Comment by JWCook** [comment]
@yelled3 @rafalslaby Would the 'filesystem backend' proposed in issue #30 do what you want?

If so, there was a PR for that (#97), which one of you could finish and resubmit, if you wanted.

**Comment by JWCook** [comment]
I'm going to close this issue for now, since there doesn't appear to be a solution for this using `sqlite` or the other existing backends, but please comment on #30 if you have thoughts on accomplishing this with a file-based backend. Thanks!
