### ISSUE TITLE
Add multiprocess and multithreaded examples to docs

### ISSUE THREAD

**Issue by rtphokie** [reclosedev/requests-cache#143]
Requests doesn't appear to be inheriting a previously applied cache inside asynchronous multiprocessing  modules such as ray and multiprocessing. 

Example error:
```
requests_cache.install_cache('my_cache')

@ray.remote
def get_the_thing_from_the_place(url):
    r = requests.get(url)
    if not r.from_cache:
        logging.warn(f"not from cache: {url}")
```
produces the error:
```
AttributeError: 'Response' object has no attribute 'from_cache'
```

when called from something like 
```
results.append(get_history.remote(myurl))
```
The error goes away when you install the cache inside the remote function, but this is very expensive and defeats the purpose of parallelizing.  

Any ideas on how to ensure a previously installed cache is available to requests inside asynchronous processes? The only solution I've found to this is to parallelize using celery workers (which keep a process running with the cache intact.) but ray and other parallelization modules are much more efficient that celery in many applications.

**Comment by JWCook** [comment]
@rtphokie This is a year and a half later, but are you still using requests-cache, and are you still running into this issue?

I don't have experience with ray in particular, but with multiprocessing in general, you're right that the global patching method (`install_cache()`) just isn't going to work across parallel processes. The best place to start would be to create a `requests_cache.CachedSession` and pass that as a parameter to each of your processes/tasks/workers.

Let me know if you try that approach, and if you run into more issues I can try to help work through them.

**Comment by rtphokie** [comment]
I still actively use requests_cache, but only for single threaded projects
since its not really thread safe, at least using the global patching method
as you mention.  I've not tried the CachedSession method but will next time
I spin up a new multithreaded project.

Thanks for reaching out,
Tony

**Comment by JWCook** [comment]
There are some recent improvements that might be relevant to thread-safety (not yet released, but will be in the near future), and it would be good to get some multithreaded/multiprocess examples added to the docs. If you would be willing to test out the current master branch sometime, that would be really helpful! Or you could wait for the next release, if you prefer.

**Comment by JWCook** [comment]
FYI, the changes mentioned above are now in the latest stable release (0.6.x), and the documentation explicitly mentions the functions that are not thread-safe (for example, [patching](https://requests-cache.readthedocs.io/en/v0.6.3/api.html#module-requests_cache.patcher) and [`CachedSession.cache_disabled()`](https://requests-cache.readthedocs.io/en/v0.6.3/api.html#requests_cache.session.CachedSession.cache_disabled)). There are also automated tests for thread safety.

It's possible that there are still be some cases that the docs and tests don't yet cover, though, and I still need to add multithreaded examples to the docs.
