### ISSUE TITLE
Can I store negative responses?

### ISSUE THREAD

**Issue by marcvs** [reclosedev/requests-cache#145]
I'm querying a number of hosts multiple times. It would be useful if requests_cache also cached negative hits, likely with a different cache time.

I know how to help myself otherwise, still I think this might be a useful feature.

**Comment by HalfWhitt** [comment]
If I understand you correctly, I was just having this same issue.

One of the optional parameters to `CachedSession()` or `install_cache()` is `allowable_codes`, a tuple that by default only includes the code 200. That means it only caches a result if your request successfully receives data.

If you change your install line to something like:
`requests_cache.install_cache('example_cache', allowable_codes=(200, 404))`

It will cache 404 (file not found) results as well. I hope this helps!

**Comment by marcvs** [comment]
It absolutely does. Thanks!
