### ISSUE TITLE
Using with OriginalSession from requests subclass 

### ISSUE THREAD

**Issue by dahifi** [reclosedev/requests-cache#146]
I'm trying to understand how to use this with a class that inherits from requests
```
class APISession(requests.Session):
    # set auth headers &c..
 
class APIClient:
    self.session = APISession()

    def _request(self, args):
        response = self.session.request(args)

    def api_call(self):
        url = '/url/endpoint'
        return self._request(url=url)

    def another_api_call(self):
        url = '/url/endpoint2'
        return self._request(url=url)
```
When I'm using Mock in tests, I have to patch APISession.request when I want to prevent an API call. I don't understand how to do that using this API. Looking at the core.py file, I may be able to swap out 

`from requests import Session as OriginalSession` for `from mymodule import APISession as OriginalSession` or changing OriginalSession's parent.

Suggestions?

**Comment by gchamon** [comment]
shouldn't you inherit from `requests_cache.CachedSession`?

**Comment by JWCook** [comment]
See #158, which I'm working on right now (by making `CachedSession` features available as a mixin class). The solution for that will also work for your case.

I'm going to close this issue as a duplicate, but please comment on #158 if you have more thoughts on this.

**Comment by JWCook** [comment]
See examples in PR #183.
