### ISSUE TITLE
HEAD caching

### ISSUE THREAD

**Issue by jayvdb** [reclosedev/requests-cache#147]
The allowed methods is only `GET` by default.

Quick tests with HEAD caching suggest it works well, even switching between GET and HEAD of the same URL appears to do the right thing.

I dont see any issues about HEAD caching.  Are there any known problems which would prevent it from being enabled by default?  Or any HEAD specific corner cases which should be added to the test suite?

**Comment by JWCook** [comment]
I also don't see a reason why `HEAD` couldn't be added as a default method. Go ahead and submit a PR if you'd still like this.
