### ISSUE TITLE
`_RawStore` doesn’t behave like `urllib3.response.HTTPResponse`

### ISSUE THREAD

**Issue by flying-sheep** [reclosedev/requests-cache#148]
Specifically, when I use `pandas.read_csv(requests.get(url, stream=True).raw)`, it’ll work when nothing is cached, but not when a cache exists.

That’s because `pandas.api.types.is_file_like` tests if `__iter__` exists on the object: https://github.com/pandas-dev/pandas/blob/v1.0.3/pandas/core/dtypes/inference.py#L130-L165

**Comment by domdfcoding** [comment]
`urllib3.response.HTTPResponse` can also act as a ContextManager, but `_RawStore` lacks an `__enter__` method so an `AttributeError` is raised.

**Comment by JWCook** [comment]
Good catch! This should be a relatively easy fix. Would one of you like to submit a PR for it?

**Comment by JWCook** [comment]
I will plan on fixing this along with other changes in #187.

**Comment by JWCook** [comment]
This is now fixed in the master branch.
