### ISSUE TITLE
Compatibility with requests_html.HTMLSession

### ISSUE THREAD

**Issue by kousu** [reclosedev/requests-cache#149]
This confuses `requests-html`:

```
import requests
import requests_cache
import requests_html

requests_cache.install_cache()
requests_cache.clear()
r = requests.get("https://github.com")
print(r.from_cache) # >> False

s = requests.Session()
r = s.get("https://github.com/")
print(r.from_cache) # >> True

s = requests_html.HTMLSession()
r = s.get("https://github.com/")
print(r.from_cache)
# >>> Traceback (most recent call last):
#  File "cache.py", line 17, in <module>
#    print(r.from_cache)
# AttributeError: 'HTMLResponse' object has no attribute 'from_cache'
```

Setting up the cache **before loading `requests_html`** works though, because it [subclasses `requests.Session`](https://github.com/psf/requests-html/blob/dc82965d66761eed3b92ff371b8af9c4b85cc725/requests_html.py#L754) which `requests-cache` is replacing:

```
import requests
import requests_cache

requests_cache.install_cache()
import requests_html

requests_cache.clear()
r = requests.get("https://github.com")
print(r.from_cache) # >> False

s = requests.Session()
r = s.get("https://github.com/")
print(r.from_cache) # >> True

s = requests_html.HTMLSession()
r = s.get("https://github.com/")
print(r.from_cache) # >> True
```

I don't know what the right solution to getting these to play nice is. For a small project just making sure to do the loading in this order is probably okay, but it'll get nasty in bigger projects.

`betamax` [makes use of](https://github.com/betamaxpy/betamax/blob/2c12cee59ac365f39497a3718eed04ab9c6ce988/src/betamax/recorder.py#L122-L126) [`request.Session.mount()`](https://2.python-requests.org/en/master/user/advanced/#transport-adapters) to redirect all requests into itself. I wonder if that would be more reliable, or maybe just as prone to collisions. :ski:

**Comment by kousu** [comment]
Maybe if both Sessions were proxies to a wrapped session, instead of subclasses of it, e.g.:

```
class Session:
    def __init__(self, wrapped_session=None, ....):
       if wrapped_session is None: wrapped_session = requests.Session
       self.wrapped_session = wrapped_session
    def getattr(self, k):
        return getattr(self.wrapped_session, k)
    # ... etc
```

Then the order of wrapping wouldn't matter as much.

But I'm just thinking outloud. This is a tricky corner case.

**Comment by kousu** [comment]
Dope project though! This is sooooo useful for me.

**Comment by JWCook** [comment]
Cooperative inheritance would be the most pythonic solution for this. Both `HTMLSession` and `CachedSession` would need to be usable as mixin classes, which wouldn't be too difficult. Same situation as #158. Similar issue here as well: https://github.com/JWCook/aiohttp-client-cache/issues/16

So your ideal session would end up looking like this:
```python
class CustomSession(HTMLMixin, CacheMixin, ClientSession):
    """Session class with features from both requests-html and requests-cache"""
```

I'll close this issue now, but please comment on #158 if you have more thoughts on this. Thanks!

**Comment by JWCook** [comment]
Done. See examples in PR #183.
