### ISSUE TITLE
Extract all urls persisted in cache

### ISSUE THREAD

**Issue by fbuchinger** [reclosedev/requests-cache#155]
Is there a way to list all URLs that are currently stored in the cache? When i checked the sqlite database, I noticed that the `urls` table is empty whereas the `responses` table just stores a hashed url(?) and its response in a blob.

**Comment by JWCook** [comment]
The `urls` table is just for `response.history`. In other words, it maps multiple redirect requests to a single cached response. If you haven't cached any requests with redirects, `urls` will be empty.

There currently isn't any way to extract the original URL from the key. The closest thing is the `BaseCache.has_url()` method, which can tell you if a given URL is cached (not taking into account request params, headers, etc.).

Getting a list of all cached URLs sounds useful, though. This could be accomplished by maintaining a third table (or collection, or hash, etc.) to store this info. It would need to be updated anytime either `urls` or `responses` is modified.

**Comment by JWCook** [comment]
In the current master branch, you can get all URLs like this:
```python
print([response.url for response in session.cache.responses.values()])
```

Note that this could potentially be a bit slow if you have a very large cache. I will also add a note about this to the docs.

**Comment by JWCook** [comment]
Also, after #195 You can now get this info (plus redirect URLs) using `session.cache.urls`.
