### ISSUE TITLE
programatically condition to disable the cache

### ISSUE THREAD

**Issue by kthulsidoss** [reclosedev/requests-cache#157]
Hi
Greetings. I want to programatically check the condition and disable the cache . Is there a **counter** available to tell how much time has elapsed for the cache to expire ? i want to use that variable and based on that i want to do few things

1.expire the cache
2.install the cache again

**Comment by JWCook** [comment]
I think the `filter_fn` parameter will do what you want. See #161 for an example.

For cache expiry, just use the `expire_after` parameter, unless I'm misunderstanding. The `created_at` time is stored in the cache along with the response, and that value is checked every time the cached response is retrieved or if `requests_cache.remove_expired_responses()` is called.
