### ISSUE TITLE
Support using requests-cache with other libraries that extend requests.Session

### ISSUE THREAD

**Issue by jeremydouglass** [reclosedev/requests-cache#158]
I would like to import `requests-cache` while working with the  [internetarchive](https://github.com/jjjake/internetarchive) library, which uses an [ArchiveSession](https://archive.org/services/docs/api/internetarchive/api.html#archivesession-objects) object subclassed from `requests.Session`. I can use `install_cache()` to monkey-patch requests, and it works, but the patch does not affect the internetarchive subclass from requests, which is my goal

Basic monkey-patch works:

```
import requests
import requests_cache
requests_cache.install_cache()
isinstance(requests.session(), requests_cache.CachedSession)
```
> True

However, the patch doesn't appear to affect the internetarchive subclass.

```
import requests
import requests_cache
requests_cache.install_cache()
import internetarchive
print(internetarchive.session.ArchiveSession.__bases__)
isinstance(internetarchive.session.ArchiveSession, requests_cache.CachedSession)
```
> (<class 'requests.sessions.Session'>,)  
> False

Any suggestions greatly appreciated.

**Comment by CharString** [comment]
In theory this could be enough:

    class CachedArchiveSession(CachedSession, ArchiveSession):
        pass

But both ArchiveSession and CachedSession do call `super().__init__()`, but they don't pass any arguments.
https://github.com/reclosedev/requests-cache/blob/master/requests_cache/core.py#L85
https://github.com/jjjake/internetarchive/blob/master/internetarchive/session.py#L101

Also, ArchiveSession doesn't accept any arguments it doesn't know and CachedSession passes any unknown arguments to the cachebackend and I haven't checked how well they handle those. So you'll have to implement an `__init__()` that accepts all keywords and passes them to the right ancestor.

    class CachedArchiveSession(CachedSession, ArchiveSession):
        def __init__(self, some_cache_arg, some_archive_arg):
            CachedSession.__init__(some_cache_arg)
            ArchiveSession.__init__(some_archive_arg)

This does result in the base `requests.Session.__init__()` to be called twice, I think. Or you can fix it in both libraries. So the inheritance is cooperative.

**Comment by JWCook** [comment]
@CharString you hit the nail on the head. Calling init twice could have some unintended consequences, though. The best solution to this would be the same as #87, or in any other case where you'd want to use both `CachedSession` and some other library that patches or extends `requests.Session`: Refactor each class to work as a mixin class.

I did something similar here: https://github.com/JWCook/aiohttp-client-cache/commit/d88c48e31657a8ba62bcabd84234c7836963a488

It would be relatively easy to do the same for requests_cache. Would one of you like to submit a PR for this? A corresponding PR for internetarchive would be needed to update `ArchiveSession`. Then you could do:
```python
CachedArchiveSession(CacheMixin, ArchiveMixin):
    pass
```

**Comment by JWCook** [comment]
Done. See examples in PR #183.
