### ISSUE TITLE
Add support for allowable_hosts

### ISSUE THREAD

**Issue by vaidik** [reclosedev/requests-cache#161]
Some kind of host filtering would be amazing so that in a script, you can choose to cache only specific hosts. Use-case for this is to cache external APIs that could be rate-limited

**Comment by JWCook** [comment]
There is a `filter_fn` parameter that could accomplish this: https://github.com/reclosedev/requests-cache/blob/master/requests_cache/core.py#L58

For some reason I don't see it [in the docs](https://requests-cache.readthedocs.io/en/latest/api.html#requests_cache.core.CachedSession), but It looks like it was added 3 years ago [in this commit](https://github.com/reclosedev/requests-cache/commit/55a081c7c6f3d8bc39e7da52116e397ff923cf82).

So something like this should do what you want:
```python
from requests_cache import CachedSession
from urllib.parse import urlparse

ALLOWED_HOSTS = ['www.example.com']

def filter_hosts(response):
    u = urlparse(response.request.url)
    return url.netloc in ALLOWED_HOSTS

session = CachedSession(filter_fn=filter_hosts)
```

I haven't actually tested that, but I think that's how it's supposed to work.

**Comment by JWCook** [comment]
After #184 is implemented, a good way to implement this may be to extend the `urls_expire_after` param, which lets you specify a list of URL glob patterns and expiration times. All that would be needed is to add a value that indicates 'do not cache'. I think 0 would work, since that's how `Cache-Control: max-age` works. Then you could do this to only cache responses from `site_1.com` and `site_2.com` + subdomains:

```python
urls_expire_after = {
    'site_1.com`: 60,
    'site_2.com`: 60,
    '*.site_2.com`: 60,
    '*': 0,  # Any URL that doesn't match won't be cached
}
session = CachedSession(urls_expire_after=urls_expire_after)
```

Or, instead of the wildard at the end (`'*'`):
```python
session = CachedSession(expire_after=0, urls_expire_after=urls_expire_after)
```

**Comment by JWCook** [comment]
This is now possible as of #255.

**Comment by robocon20x** [comment]
> After #184 is implemented, a good way to implement this may be to extend the `urls_expire_after` param, which lets you specify a list of URL glob patterns and expiration times. All that would be needed is to add a value that indicates 'do not cache'. I think 0 would work, since that's how `Cache-Control: max-age` works. Then you could do this to only cache responses from `site_1.com` and `site_2.com` + subdomains:
> 
> ```python
> urls_expire_after = {
>     'site_1.com`: 60,
>     'site_2.com`: 60,
>     '*.site_2.com`: 60,
>     '*': 0,  # Any URL that doesn't match won't be cached
> }
> session = CachedSession(urls_expire_after=urls_expire_after)
> ```
> 
> Or, instead of the wildcard at the end (`'*'`):
> 
> ```python
> session = CachedSession(expire_after=0, urls_expire_after=urls_expire_after)
> ```

thank you so much, im a newbie and don't know how to use filter_fn.
