### ISSUE TITLE
Non-global behavior (per session)?

### ISSUE THREAD

**Issue by jaraco** [reclosedev/requests-cache#165]
The README suggests to me that requests-cache applies to all requests. This behavior means I cannot use this functionality in a library that other applications might invoke, because by enabling the cache, it will affect the behavior globally, including unrelated requests calls.

Is there any way to use this functionality that's associated with a particular session or otherwise restrict the requests that are affected?

**Comment by JWCook** [comment]
Absolutely. Just use `requests_cache.CachedSession` in place of `requests.Session`. Managing your own session object is IMO a better approach than using the global patching functions (`requests.cache.install_cache()`, etc.).

This could probably be better explained in the documentation. I'll leave this issue open as a reminder to update them.
