### ISSUE TITLE
Blacklist urls?

### ISSUE THREAD

**Issue by pryme-svg** [reclosedev/requests-cache#166]
In my python code, there are certain urls that can be cached, and certain ones that should not be cached, for example https://zenquotes.io/api/random

Is there a way to prevent that url from being cached?

**Comment by pryme-svg** [comment]
https://github.com/reclosedev/requests-cache/blob/6717a336430eb7e6fe17e75c5517f3076ca85b42/requests_cache/core.py#L164

**Comment by JWCook** [comment]
For reference, URL glob patterns are now supported: https://requests-cache.readthedocs.io/en/stable/user_guide.html#url-patterns
