### ISSUE TITLE
Fix readthedocs build

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#174]
It appears that the documentation at https://requests-cache.readthedocs.io isn't getting updated. Either it's not getting triggered off of the master branch, or the build is failing, but I'm not able so see build logs. The build works fine locally (`make -C docs html`), but differences in the readthedocs build environment could be causing it to fail.

I (or someone else!) could run the requests-cache documentation build within the readthedocs Docker image to see what's going on.

**Comment by JWCook** [comment]
@reclosedev Would you be able to take a look at the readthedocs build, and post the traceback here if there is one?

Also, if you would like to add me to the project on readthedocs as a maintainer, that would be helpful well!

**Comment by JWCook** [comment]
Update: Turns out non-maintainers on readthedocs can see build logs: https://readthedocs.org/projects/requests-cache/builds/

So there are no failing builds, they just aren't getting triggered at all.  The last build was Nov. 9, 2017 (version 0.4.13), so these must have been manually triggered.

**Comment by reclosedev** [comment]
Looks like there was no hooks, or it was deleted somehow. I've updated settings at readthedocs.org

**Comment by JWCook** [comment]
Great, thanks!
