### ISSUE TITLE
Add automated PyPI releases based on git tags

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#179]
@reclosedev Something I would like to add -- but can't currently -- is release automation based on git tags. See [example build from another project here](https://github.com/JWCook/pyinaturalist/blob/dev/.github/workflows/build.yml#L76-L95), and [related GitHub docs here](https://docs.github.com/en/actions/guides/building-and-testing-python#publishing-to-package-registries).

All that will require is for you to create a PyPI API key and add it to the [project secrets](https://docs.github.com/en/actions/reference/encrypted-secrets) as `PYPI_TOKEN`. It looks like Code Shelter may be unable to do that since only the repo owner can add secrets. [Link to related discussion here](https://codeshelter.zulipchat.com/#narrow/stream/186993-projects/topic/requests-cache/near/227962808).

Is that something you would be able to do for me? If not, we can still do manual releases, but this would make it a lot easier. Thanks!

**Comment by reclosedev** [comment]
I've added API key as `PYPI_TOKEN` secret.

**Comment by JWCook** [comment]
Great, thank you!

**Comment by JWCook** [comment]
I just tested it out with a pre-release build, and it works! Build `requests-cache-0.6.0.dev0` is now on pypi, which is only installable with `pip install --pre requests-cache`.

`pip install requests-cache` still installs version 0.5.2.
