### ISSUE TITLE
License type not detected by GitHub

### ISSUE THREAD

**Issue by FredHappyface** [reclosedev/requests-cache#182]
Hello,

For some reason GitHub isn't giving your license a nice name (not too sure why that is). Anyway, not sure if that's something you want to take a look at or point out the type of license so anyone reading the repo can quickly tell what it is under. Though I've just double checked pypi and can see it there

Thanks :D

(FYI to anyone who's missed it:: BSD License)

**Comment by JWCook** [comment]
Good call. GitHub can sometimes be picky about formatting when reading the license file. Example here: https://github.com/modxcms/revolution/issues/14023

PyPI, on the other hand, gets that info from metadata in `setup.py` and/or [`setup.cfg`](https://github.com/reclosedev/requests-cache/blob/master/setup.cfg#L9).

 I'll poke at it a bit and see if I can get GitHub to recognize it.

**Comment by FredHappyface** [comment]
Yeah I've experienced similar things in the past. Also not friendly to unpopular licenses (not that this applies here, I know)

**Comment by JWCook** [comment]
There, looks like that did it. GitHub correctly recognizes it as BSD-2 now.
