### ISSUE TITLE
Feature proposal/question: Add support for cache headers

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#192]
I would like to poll the audience about what kinds of features you might be interested in for (optionally) making requests-cache behave more like a browser cache. Please comment if this is something that would be useful to you, and which features you would consider most important.

Personally, I find requests-cache's way of handling cache expiration more useful than relying on headers, since most use cases for consuming content from a python application are different from surfing the internet from a browser. That being said, there are plenty of cases where cache headers (in both responses and requests) would be quite useful. This is something the [CacheControl](https://github.com/ionrock/cachecontrol) library already does well, so we definitely don't need to duplicate everything it does, but there are some incremental improvements we could make that I think would be reasonable.

Here are features that I've roughly ranked from "easy to implement/broad usage" to "more complex to implement/niche usage":

# Basic features
Basic features to start with:

- [x] Anything different than current default behavior should be an **opt-in feature**, for example with a parameter like `CachedSession(cache_control=True)`.
- [x] `Cache-Control: max-age`: A relative expiration time in seconds that would set our `expire_after` value.
- [x] `Expires`: An absolute expiration time, overridden by `max-age` if both are provided.
- [x] `Cache-Control: no-store`: Disables caching (both read and write) for an individual response. If a server sends this header, there is likely a good reason for it.

# Advanced features
Some lower-priority, but probably useful features to consider:
- [x] Request headers `Cache-Control: max-age` or `no-cache` sent by the client could be used to set expiration on a per-request basis. This is already possible using `CachedSession.request(expire_after=...)`, so I could see this being useful if:
  - requests-cache is being added to an application that already uses these headers
  - requests-cache is being used in a library used by other libraries or applications (not recommended, but possible)
- [ ] `Cache-Control: immutable`: I'm not sure how common this one is, and it's not supported by all browsers, but it could be a fairly straightforward indication that the response should never expire.
- [ ] Request header `Cache-Control: stale-if-error`: Another non-standard one that isn't supported by all browsers. This could be used, for example, to set `CachedSession.old_data_on_error` on a per-request basis.

# ???
I don't know if there would be much need to support the following headers, but please comment if you have a concrete use case for one of them:
* Request header `Cache-Control: stale-while-revalidate` is also interesting, but the expected behavior in requests-cache would be a little less straightforward. See: https://web.dev/stale-while-revalidate/
* `If-Modified-Since` request headers and `304: Not Modified` responses: These would be feasible to handle, but this is pretty niche. We can implement these if someone has a concrete use case for them.
* `Cache-Control: max-stale` and `min-fresh` client request headers: Same thing, feasible but niche.
* `Cache-Control: must-revalidate`: The behavior for this as a "suggestion" rather than a deterministic rule seems fairly browser-specific.
`Cache-Control: public, private, s-maxage, proxy-revalidate`, and `no-transform`: These are mainly relevant for shared (proxy) caches. I'm fairly sure any application using requests-cache would be considered a private cache and not a proxy cache.

**Comment by CyberShadow** [comment]
> `If-Modified-Since` request headers and `304: Not Modified` responses: These would be feasible to handle, but this is pretty niche. We can implement these if someone has a concrete use case for them.

Here is a concrete use case for ``Last-Modified`` + `If-Modified-Since` / `ETag` + `If-None-Match`: making conditional requests to the GitHub API. Not only does GitHub make use of these to return a 304 Not Modified on a hit, but, such hits **do not count against the rate limit**. This means that it is possible to create applications which poll GitHub as often as necessary without worrying about running into rate limits.

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests

**Comment by JWCook** [comment]
Interesting, thanks for the example!

I have started working on adding support for `ETag` + `If-None-Match` + `304: Not Modified` in #332, so I'll ask some follow-up questions there.
