### ISSUE TITLE
support etags and other cache headers?

### ISSUE THREAD

**Issue by kgk** [reclosedev/requests-cache#198]
Are there plans to support normal cache headers from web servers ?   I am working with several site that do provide proper headers and am wondering if this is in the plan or should I try CacheControl ?

**Comment by JWCook** [comment]
CacheControl would probably be your best option for now. I have been thinking about adding support for cache headers at some point. I made issue #192 to collect ideas for that. Please comment there if there are particular features you'd most like to see.

**Comment by JWCook** [comment]
Basic Cache-Control header support is available in 0.7: https://requests-cache.readthedocs.io/en/stable/user_guide.html#cache-control

ETag support will likely be added in a future release: #332
