### ISSUE TITLE
v0.6 Release testing/feedback

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#200]
We are just about finished with all the bugfixes, maintenance items, and new features that I wanted to fit into the next release. If nothing else comes up during testing, I would like to create a new **release on Friday, April 9.**

Since this includes a large number of changes, I would appreciate it if any other users or contributors would **test out these changes with whatever code you already happen to have that uses `requests-cache`**. You can either check out the master branch, or try the pre-release build:
```python
pip install -U --pre requests-cache
```

See:
* Updated documentation at [readthedocs](https://requests-cache.readthedocs.io)
* Full list of PRs and issues included in the [v0.6 milestone](https://github.com/reclosedev/requests-cache/milestone/1?closed=1)
* High-level summary of changes in [HISTORY.md](https://github.com/reclosedev/requests-cache/blob/master/HISTORY.md)
* Updated list of contributors in [CONTRIBUTORS.md](https://github.com/reclosedev/requests-cache/blob/master/CONTRIBUTORS.md)

**Comment by coryairbhb** [comment]
I get the following
AttributeError: Can't get attribute '_Store' on <module 'requests_cache.backends.base' from '/usr/local/lib/python3.9/site-packages/requests_cache/backends/base.py'>

**Comment by JWCook** [comment]
@coryairbhb Thanks for the heads up, I'll get that fixed shortly.

The cache serialization has changed, so data cached with a previous version won't be retrievable with 0.6. When that happens, though, it's supposed to simply make a new request instead of raising an error.

**Comment by JWCook** [comment]
Alright, this should now be fixed.

**Comment by coryairbhb** [comment]
Verified it works but I believe session.remove_expired_responses() causes the same issue.

**Comment by JWCook** [comment]
Fyi, I also added an [example script](https://github.com/reclosedev/requests-cache/blob/master/examples/convert_cache.py) to convert an existing cache to the new format, in case anyone really wants to keep their current data after updating.

**Comment by JWCook** [comment]
@1kastner @Ax6 @Demborg @FredHappyface @JohnVillalovos @Kylotan @MaxBareiss @bachya @backbord @borisdan @chanfr @chrahunt @coryairbhb @dahifi @domdfcoding @elad661 @fbuchinger @flying-sheep @gchamon @gjedeer @gwillem @jaraco @jayvdb @jhermann @jordansamuels @kgk @kousu @libbkmz @llazzaro @olivierdalang @olymk2 @pslacerda @pslacerda @reclosedev @robmosca @shakeyourbunny @shoeffner @slinlee @ximo1984

FYI, changes you contributed, suggested, and/or commented on have been released in 0.6. See the [changelog](https://github.com/reclosedev/requests-cache/blob/master/HISTORY.md) for details. Thanks everyone for the contributions and feedback! Please test out the new version when you get the chance, and report any issues you come across.
