### ISSUE TITLE
Bypass cache on demand?

### ISSUE THREAD

**Issue by coryairbhb** [reclosedev/requests-cache#205]
Is there a way to bypass cache on demand when needed?
Then, cache the new response?

**Comment by coryairbhb** [comment]
The, cache the new response?

**Comment by coryairbhb** [comment]
I figured out how to disable cache
s = CachedSession()
with s.cache_disabled():
    s.get('http://httpbin.org/ip')

but, how would I insert the new request in the cache?

**Comment by JWCook** [comment]
I'm closing this issue for now, but please comment on #98 if that's a feature you'd like, or if you have thoughts on how you'd like that to work. Thanks!

**Comment by JWCook** [comment]
Fyi, this is now possible in the master branch:
```python
CachedSession.cache.save_response(response)
```
