### ISSUE TITLE
Use thread-local connections for SQLite backend

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#213]
I believe multi-threaded performance with SQLite could be significantly improved by using thread-local connections, and (optionally?) keep them open until explicitly closed. Currently, a new connection is created for every read/write operation (unless `bulk_commit()` is used).

Another possible improvement to look into (maybe as a separate issue) would be to add a write queue shared across threads instead of using a lock to prevent concurrent writes.

**Comment by jsemric** [comment]
I'd like to work on this issue

**Comment by JWCook** [comment]
@jsemric That would be great! The help would be appreciated. I have some unfinished changes in [this branch](https://github.com/JWCook/requests-cache/commits/sqlite-threadlocal) (see [sqlite.py](https://github.com/JWCook/requests-cache/blob/sqlite-threadlocal/requests_cache/backends/sqlite.py)), but don't have time to finish them right away. You could reuse some of that code if you want, but feel free to do it a different way.

A couple points that I wasn't completely sure about yet:
1. Should we make the default behavior to keep the connection(s) open, or should that be an opt-in feature? The main downside is that this will require users to call `close()` manually.
2. Will this make `bulk_commit()` redundant, or is that still useful?
3. Are there any drawbacks to using `check_same_thread=False` to allow concurrent reads, and using a lock to prevent concurrent writes?

What do you think?

**Comment by jsemric** [comment]
Thanks for the a prompt response. Here are my suggestions:

 1. I would not bother closing the connection. Just create one for each thread. I think if we commit changes after each write it should not have any impact.
 2. Bulk commit still allows committing multiple writes at once. We could create some bench-marks to test whether it improves performance.
 3. Based on [sqlite documentation](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect), either we should use `check_same_thread=False` with locks or remove the lock. Sqlite should be able to serialize writes from multiple connections.

**Comment by JWCook** [comment]
Thanks for the contribution! These changes are in pre-release build `0.7.0.dev255`.

The only issue I found was that the initial `CREATE TABLE` needs to happen in a shared connection; otherwise there seems to be a race condition in which one thread can attempt to access the table before it's created.

**Comment by JWCook** [comment]
I ran some benchmarks to compare `check_same_thread=False` with a lock vs. defaults and no lock. Even with 20 threads running at once, averaged over 160 writes, there's almost no performance difference; about 10 microseconds per write, which could just be due to randomness.

I also timed `bulk_commit()` vs. committing after each write, and you're right, `bulk_commit()` is still many times faster.
