### ISSUE TITLE
Use pytest-httpbin

### ISSUE THREAD

**Issue by jayvdb** [reclosedev/requests-cache#221]
Currently the tester needs to manually set up httpbin before running the tests.

pytest-httpbin does that automatically.

**Comment by JWCook** [comment]
Thanks for the suggestion. I did look into pytest-httpbin while working on #169, but for reproducibility across a local machine, CI builds, and other environments, it's hard to beat containers. I would really prefer to stick with Docker for any services we need to test against. For example, pytest-httpbin uses a different web server than httpbin.org or the httpbin container, so it could potentially have different behavior locally vs. in a GitHub Actions runner.

Httpbin is already included in `docker-compose.yml`, and running those containers is required for everything else under `tests/integration`. If you want to just run unit tests (which don't hit any services), you can run `pytest tests/unit`. There's more info in the [contributing guide](https://github.com/reclosedev/requests-cache/blob/master/CONTRIBUTING.md#testing).

Are you in an environment where it's difficult or impractical to run containers?

**Comment by jayvdb** [comment]
I am building and testing requests-cache in a network-isolated-VM https://build.opensuse.org/package/show/home:jayvdb:branches:devel:languages:python/python-requests-cache
I would prefer to be running as many tests as possible to ensure compatibility with the other dependencies, which are constantly being modified triggering new builds each time.
I can install httpbin onto the worker and run it, so I'll do that if using pytest-httpbin is desirable.

**Comment by JWCook** [comment]
Gotcha, that makes sense. Since there might be others out there with a similar setup, we could probably find a compromise that would make that easier without making pytest-httpbin the default.

Maybe something like adding a wrapper fixture that autouses the `pytest_httpbin.httpbin_both` fixture if:
1. httpbin isn't already running on `localhost:80` and
2. pytest-httpbin is installed

I'm open to other suggestions, though.

**Comment by jayvdb** [comment]
That sounds great.  Ideally all of https://repology.org/project/python:requests-cache/versions are in the same boat, but many are likely happy to just run unit tests.  

IMO the pytest-httpbin support would be considered experimental, i.e. those of us that are using it are expected to keep it working.

I would be happy to have an explicit envvar _USE_PYTEST_HTTPBIN to trigger using pytest-httpbin.  That avoids the need to check `localhost:80`.

**Comment by JWCook** [comment]
Sounds good. There's also an `HTTPBIN_URL` envvar you could set, if that would work:
https://github.com/reclosedev/requests-cache/blob/f6a8f325b6cb1b4c4fab77c3860df2842ec5aaa2/tests/conftest.py#L26-L29

**Comment by JWCook** [comment]
Is this something you'd like to submit a PR for? Otherwise, I can probably get around to this within the next week or two.

Also, could you point me to some docs on how packaging python libraries as RPMs (and other system packages) works? I'd like to get a better idea of what happens in between publishing a release on PyPi and getting that published to a package repo for openSUSE (or another distro).

**Comment by jayvdb** [comment]
I'd like to, but doubt I will have time.

https://build.opensuse.org/request/show/884522 is my request to upgrade this package in openSUSE.
I first needed to get the url-normalize dependency accepted https://build.opensuse.org/request/show/884161
That will be the first hurdle for distros, and you can see that there isnt many distros across it yet at https://repology.org/project/python:url-normalize/versions . It doesnt provide tests in https://files.pythonhosted.org/packages/ec/ea/780a38c99fef750897158c0afb83b979def3b379aaac28b31538d24c4e8f/url-normalize-1.4.3.tar.gz , so packagers usually look to the git repo for a versioned tarball with tests, but then https://github.com/niksite/url-normalize doesnt have a setup.py , so they need to use poetry in their build scripts, and most distros havent done that yet, c.f. https://repology.org/project/python:poetry/versions / https://repology.org/project/poetry/versions / https://repology.org/project/poetry-core/versions .

**Comment by JWCook** [comment]
Okay, that's good to know. Sorry for the hassle with adding the extra dependency!

Besides making tests easier to run, is there anything else than can be done on this end to make the RPM packaging process easier?

Also, just a heads up, I plan to get a small patch release out sometime this week (0.6.1). If I have time, I'll try to get some changes for pytest-httpbin included in that.

**Comment by jayvdb** [comment]
`requests-cache/__init__.py` shouldnt have a hashbang.

I am also concerns that the tests mention redis and mongo and other deps, and those tests pass when I havent included those services.  It would be helpful to be able to test against a real redis, as all distros have that packaged, and the mock redis responses could have been from a different version to the one currently available.  mongo isnt in openSUSE Tumbleweed IIRC, so that doesnt interest me.

Adding new deps is good.  But the main problem is url-normalize doesnt include tests in their sdist.  That complicates setting up the dependency tree for distros.

**Comment by JWCook** [comment]
> `requests-cache/__init__.py` shouldnt have a hashbang.

Good catch, I'll remove that.

> I am also concerns that the tests mention redis and mongo and other deps, and those tests pass when I havent included those services.

I haven't yet gotten around to refactoring those tests, but it is on my todo list (#212). One small improvement would be to explicitly mark them with `pytest.mark.skip` if the optional dependencies aren't installed, so it would at least be reflected in the pytest output. Or do you think it would be better to just let them fail instead?

>  It would be helpful to be able to test against a real redis

Sure, I think all that would take is adding another environment variable to set the Redis host, if something other than `redis://localhost` (and other connection args, if needed)

> the mock redis responses could have been from a different version to the one currently available.

There aren't any mock responses for the Redis tests currently. Tests are run against [this image](https://hub.docker.com/r/bitnami/redis) locally, and against [this image](https://hub.docker.com/_/redis) via [this GitHub Action](https://github.com/supercharge/redis-github-action) for CI jobs. We could test against multiple Redis versions (currently just 6.x) in GitHub Actions, if you think that would be valuable.

>  But the main problem is url-normalize doesnt include tests in their sdist

The issue there may be that poetry doesn't seem to let you include tests without also installing them as a package; see https://github.com/python-poetry/poetry/issues/2513 . I can't think of any good solutions for that off the top of my head.

**Comment by jayvdb** [comment]
If the missing deps are python, tests should fail if they are missing, otherwise packagers will often see the build was green and not look at the logs.  Non-Python and especially non-free optional deps should skip if missing, but failing is also ok.  packagers/testers can always use pytest args to skip tests they dont want to run.

The default redis port is able to be used, so using redis://localhost is not a problem.

@dephell is a better tool for creating the sdist, but it does have a few bugs that occasionally make it incompatible with poetry - the maintainer is quite responsive.

**Comment by JWCook** [comment]
>  tests should fail if they are missing, otherwise packagers will often see the build was green and not look at the logs.

That makes sense. I'll update that when I get around to #212.

> The default redis port is able to be used, so using redis://localhost is not a problem.

In that case, you should be able to `pip install redis` and then run `pytest tests/integration/test_redis.py` in that environment without any other changes needed.

**Comment by jayvdb** [comment]
Done that - the redis tests pass.

These are the ones which were running previously and concerned me as no redis was installed.  How could they pass, unless they were mocked..?

`tests/unit/test_thread_safety.py::test_caching_with_threads[redis-..] PASSED [ ..%]`

**Comment by JWCook** [comment]
Hmm, tests fail for me both locally and in GitHub actions ([logs here](https://github.com/reclosedev/requests-cache/runs/2320435297)) if Redis isn't available.

**Comment by JWCook** [comment]
Oh, I see, that's in `tests/unit/test_thread_safety.py`. You're right, those (and all the other tests under `tests/unit`) aren't testing actual backend connections.

The tests under `tests/integration` are run against real databases.

**Comment by JWCook** [comment]
...But taking a closer look at that particular test module (`test_thread_safety.py`) did make me realize that those tests are incorrect and aren't actually testing what they're supposed to. I'll get that fixed soon.

**Comment by JWCook** [comment]
@jayvdb Changes for pytest-httpbin are in the master branch now, as well as a 'fail fast' check for DynamoDb, MongoDb, and Redis tests. Give that another try for me when you get the chance.

**Comment by jayvdb** [comment]
`USE_PYTEST_HTTPBIN=true pythonX.Y -m pytest -k 'not (dynamodb or gridfs or mongodb)'` WFM.

Thank you!

**Comment by JWCook** [comment]
Great! These changes are now in requests-cache 0.6.1.

**Comment by JWCook** [comment]
Looks like I had made a mistake in `MANIFEST.in`, and tests didn't correctly get included in the sdist this time. I pushed out 0.6.2 to fix that.
