### ISSUE TITLE
AttributeError: Can't get attribute '_Store' on upgrade of 0.5.x to 0.6.0

### ISSUE THREAD

**Issue by glensc** [reclosedev/requests-cache#223]
From the changelog, I read that the previous cache will be just outdated:
- https://github.com/reclosedev/requests-cache/blob/v0.6.0/HISTORY.md

but using the advanced example to inspect cache:
- https://requests-cache.readthedocs.io/en/v0.6.0/advanced_usage.html#cache-contents

and with existing SQLite cache file last updated by 0.5.2:

```py
from requests_cache import CachedSession

session = CachedSession()
print(session.cache)
print('Cached URLS:', session.cache.urls)
```

The code ends up with a uncaught exception:

```
AttributeError: Can't get attribute '_Store' on <module 'requests_cache.backends.base' from '/usr/local/lib/python3.9/site-packages/requests_cache/backends/base.py'>
```

the `Can't get attribute '_Store'` problem goes away if I delete the previous `cache.sqlite`, but wasn't the upgrade supposed to be automatic?

**Comment by glensc** [comment]
so the examples are broken too:
- https://github.com/reclosedev/requests-cache/blob/v0.6.0/examples/basic_usage.py

**Comment by glensc** [comment]
- https://github.com/reclosedev/requests-cache/blob/v0.6.0/examples/session_patch.py

```
AttributeError: 'DbCache' object has no attribute 'urls'
```

**Comment by glensc** [comment]
seems I failed to update the module to 0.6.0, but with 0.6.0 I still have error:

```py
from requests_cache import CachedSession

session = CachedSession()
print(session.cache)
print('Cached URLS:', session.cache.urls)
```

```
AttributeError: Can't get attribute '_Store' on <module 'requests_cache.backends.base' from '/usr/local/lib/python3.9/site-packages/requests_cache/backends/base.py'>
```

the `Can't get attribute '_Store'` problem goes away if I delete the previous `cache.sqlite`, but wasn't the upgrade supposed to be automatic?

**Comment by JWCook** [comment]
You're correct, that's not supposed to happen. Could you post a full traceback?

**Comment by glensc** [comment]
```py 
from requests_cache import CachedSession

session = CachedSession()
print(session.cache)
print('Cached URLS:', session.cache.urls)
```

```
➔ python3 t.py
redirects: 0
responses: 1539
Traceback (most recent call last):
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/t.py", line 5, in <module>
    print('Cached URLS:', session.cache.urls)
  File "/usr/local/lib/python3.9/site-packages/requests_cache/backends/base.py", line 32, in urls
    return sorted([r.url for r in self.responses.values()])
  File "/usr/local/lib/python3.9/site-packages/requests_cache/backends/base.py", line 32, in <listcomp>
    return sorted([r.url for r in self.responses.values()])
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_collections_abc.py", line 869, in __iter__
    yield self._mapping[key]
  File "/usr/local/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 180, in __getitem__
    return self.deserialize(super().__getitem__(key))
  File "/usr/local/lib/python3.9/site-packages/requests_cache/backends/base.py", line 176, in deserialize
    return self._serializer.loads(bytes(item))
AttributeError: Can't get attribute '_Store' on <module 'requests_cache.backends.base' from '/usr/local/lib/python3.9/site-packages/requests_cache/backends/base.py'>
```

**Comment by JWCook** [comment]
Oh! Derp. That was already handled in `get_response()`, but I didn't think to handle that in `urls` as well. I'll get that fixed shortly.

Also, if needed, you can delete the offending cache items without deleting the whole database using `CachedSession.remove_expired_responses()`.

**Comment by JWCook** [comment]
@glensc Fixed in the master branch. There will be a patch release sometime next week. Thanks for reporting this!

**Comment by glensc** [comment]
@JWCook I would rather not implement any logic into my application dealing with the upgrade. how do I even know I need to run the remove_expired_responses that it was the point of the uprade?

**Comment by JWCook** [comment]
I should have been more clear. You do not need to add any extra logic to your application. I just mentioned that as a short-term fix until I get a patch release out.

Normally, expired and invalid responses will only be deleted or replaced the next time they are accessed. `remove_expired_responses()` is available for manual cleanup, if you happen to have a very large cache with lots of old data, and you want to free up disk space (while keeping any non-expired data).

**Comment by glensc** [comment]
Thanks. Luckily I can just postpone this library update until it became suitable :) In other words, the application that uses this library has pinned requests-cache to exact version.
