### ISSUE TITLE
Debug messages appeaering with 0.5.2 -> 0.6.0 update

### ISSUE THREAD

**Issue by glensc** [reclosedev/requests-cache#224]
Seems `requests-cache` is using root logger and prints debug info with logging.info, should use logging.debug at least:

```
$ ./plex_trakt_sync.sh cache
INFO: Patching requests.Session with class: type
INFO: Initializing backend: sqlite
INFO: Initializing DbPickleDict with serializer: <class 'module'>
INFO: Using a secret key to sign cached items is recommended for this backend
INFO: Initializing DbDict with serializer: <class 'module'>
INFO: Using a secret key to sign cached items is recommended for this backend
redirects: 0
responses: 1539
```

**Comment by glensc** [comment]
seems current workaround is to limit this module logging:

```py
# somewhere in application startup
logging.getLogger('requests_cache').setLevel(logging.WARNING)
```

**Comment by JWCook** [comment]
I bumped most of the logging messages down to debug level.

Also, this library only logs to the `requests_cache` logger, not the root logger, and doesn't configure any logging handlers by default.

**Comment by glensc** [comment]
For posterity, the log level was changed in https://github.com/reclosedev/requests-cache/pull/225

**Comment by glensc** [comment]
@JWCook I might have used the wrong terminology, but logs from this library started to appear on the console in my project, as it logs levels above info to the terminal.

here's how that app configures it's logger:
- https://github.com/Taxel/PlexTraktSync/blob/0.6.42/plex_trakt_sync/logging.py

**Comment by JWCook** [comment]
What info do you want to see in stdout? `INFO`+ messages from just your own application, or messages from all libraries your application uses?

**Comment by glensc** [comment]
@JWCook not interested in seeing any messages from requests-cache at all. but it's acceptable if requests-cache uses debug log level, as terminal uses only levels with >= INFO.

maybe requests-cache debugging should be feature flag, i.e it needs to be enabled first via some environment variable or method or class constant.

to re-iterate: for my application, it's fine if requests-cache does not emit any messages above 'debug' log level by default.

**Comment by JWCook** [comment]
There is already a standardized way to configure logging, and it's all in the stdlib `logging` module. What the logging config in your link is saying is "show me logging messages from *everything*, regardless of where it came from." That's what [`logging.basicConfig()`](https://docs.python.org/3/library/logging.html#logging.basicConfig) does, it just configures the root logger. Any other library you're using that has `logging.info` statements will then show up, and there is nothing unique about requests-cache in that regard.

If what you want is to only see messages from your own application, then only configure the logger for your application. In your case, that logger would be `logging.getLogger('PlexTraktSync')`.

**Comment by glensc** [comment]
@JWCook in that application trakt and plex debug entries are also logged (on purpose) to application file log (not terminal).

the only breaking change was that 0.5.x used no logging and 0.6.0 used info log level, so these end up in the console (terminal).

but I think you changed info -> debug. I have not verified were all log calls changed or just a few.
