### ISSUE TITLE
Cached Sessions leave open sockets idle when finished

### ISSUE THREAD

**Issue by ReagentX** [reclosedev/requests-cache#230]
### The problem
`CachedSession()` objects do not close their sockets when they are finished being used:

```log
❯ python -m unittest tests.example.Test.test_requests_cache
~/.pyenv/versions/3.9.2/lib/python3.9/unittest/case.py:550: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('REDACTED', REDACTED), raddr=('REDACTED', 443)>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
~/.pyenv/versions/3.9.2/lib/python3.9/unittest/case.py:550: ResourceWarning: unclosed <ssl.SSLSocket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('REDACTED', 50815), raddr=('REDACTED', 443)>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.
----------------------------------------------------------------------
Ran 1 test in 0.252s

OK
```

### Expected behavior
`CachedSession()` objects close their sockets when they are finished being used.

```log
❯ python -m unittest tests.example.Test.test_requests_cache
.
----------------------------------------------------------------------
Ran 1 test in 0.252s

OK
```

### Steps to reproduce the behavior

Create `tests/example.py` and fill it with this code:

```python
import unittest


class Test(unittest.TestCase):
    """
    Tests requests_cache
    """

    def test_requests_cache(self):
        from requests_cache import CachedSession
        session = CachedSession()
        response = session.get('https://google.com')
```

Run with `python -m unittest tests.example.Test.test_requests_cache`

### Workarounds
_Is there an existing workaround for this issue?_

### Environment
- requests-cache version: `requests_cache==0.6.0`
- Python version: Python 3.9.2
- Platform: MacOS 11.2.3 (20D91)

**Comment by JWCook** [comment]
Interesting. I'm only able to reproduce that by running with unittest. The tests for requests-cache require pytest, which appears to not raise any warnings when running that same test.

It also looks like `CachedSession` is behaving the same as `requests.Session` here. If you make the same test for just requests without requests-cache:
```python
import unittest

class Test(unittest.TestCase):
    def test_requests(self):
        from requests import Session
        session = Session()
        response = session.get('https://google.com')
```
And run it with unittest, you will see the same warning. From [this comment](https://github.com/psf/requests/issues/3912#issuecomment-284328247) in the requests repo:
> This warning happens because Requests uses a keep-alive model that means we try not to explicitly close sockets in many cases. 

In both cases, I'm not sure why there would be warnings with unittest but not pytest, but likely has something to do with unittest's `setUp`/ `tearDown` logic vs. pytest fixture logic. To make sure all sockets are closed after a `unittest.TestCase`, you may need to do something like:
```python
def tearDown(self):
    self.session.close()
```

**Comment by JWCook** [comment]
@ReagentX Does this answer your question, or do you still have concerns about this?

**Comment by ReagentX** [comment]
Yeah this makes sense, thanks for the info.
