### ISSUE TITLE
Unexpected behavior of `response.raw.read(decode_content=...)` for streamed, encoded responses

### ISSUE THREAD

**Issue by shiftinv** [reclosedev/requests-cache#232]
### The problem
If caching is used and response streaming is enabled (`.get(..., stream=True)`), `response.raw.read(decode_content=True)` fails for both the base `urllib3.response.HTTPResponse` (returned initially) and `requests_cache.response.CachedHTTPResponse` (returned on subsequent requests). The former returns an empty bytes object (`b''`), while the latter raises a `urllib3.exceptions.DecodeError`.

The cause of this issue seems to be the fact that `CachedResponse.__init__` reads `original_response.content`, which is automatically decoded by requests, and uses that to re-initialize `raw._fp`, which will be decoded again when `raw.read(decode_content=True)` is called later on:
https://github.com/reclosedev/requests-cache/blob/057c8a33718f8472ea4bc76d43faf0a1445eadd5/requests_cache/response.py#L53-L56

This also means that `response.raw.read(decode_content=False)` will always return decoded data if caching is enabled, whereas the raw (encoded) bytes would be returned with caching disabled (i.e. the original behavior).

### Expected behavior
`response.raw.read(decode_content=...)` should return the same encoded/decoded data, regardless of whether `CachedSession` or `requests` is used.

### Steps to reproduce the behavior
```python
import requests
from requests_cache import CachedSession

# original requests behavior
res = requests.get('https://httpbin.org/gzip', stream=True)
assert b'gzipped' in res.raw.read(decode_content=True)


session = CachedSession(backend='memory')

# uncached response
res = session.get('https://httpbin.org/gzip', stream=True)
print(res.raw.read(decode_content=True))  # prints b''

# cached response
res = session.get('https://httpbin.org/gzip', stream=True)
res.raw.read(decode_content=True)  # raises `DecodeError`
```

### Workarounds
For decoding contents: only set `decode_content=True` if the response was not written to cache or retrieved from cache, for example by checking the type of `response.raw._fp`.  
There doesn't seem to be a workaround for `response.raw.read(decode_content=False)` returning decoded data, other than re-encoding it.

### Environment
- requests-cache version: `0.6.2`
- Python version: `3.8.5`
- Platform: Debian 10

**Comment by JWCook** [comment]
Thanks for the thorough details! That's quite helpful.

Is this something you'd be interested in submitting a PR for, or do you have any suggestions on the best way to fix this? Otherwise, I should be able to look into this more within the next week or so.

**Comment by shiftinv** [comment]
I was thinking about a possible solution to this problem while trying to come up with a workaround earlier, but I haven't tried implementing any changes so far.  
From what I can tell, one option would be to cache the raw (possibly encoded) bytes instead of the decoded `.content` property... that will likely break backwards compatibility though.

I'll see if I can figure something out, and will open a PR in case I find a proper solution.

**Comment by JWCook** [comment]
I was thinking along the same lines. So I guess the main decision is to either:
1. Cache (possibly) encoded data, and decode when accessed either via `response.content` or `response.raw.read(decode_content=True)`
2. Cache decoded data, and (possibly) encode when accessed via `response.raw.read(decode_content=False)`, depending on original encoding. Also fix resetting `raw._fp`.

Off the top of my head, I'm not sure which would be preferable.

**Comment by shiftinv** [comment]
Both have their advantages and disadvantages, it's difficult to tell which one would be easier to implement and maintain :/

1. Cache (possibly) encoded data
    - (+) No encoding/compression overhead for `decode_content=False`
    - (+) Keeps exact original response encoding intact
    - (-) Have to decode/decompress once every time the response is retrieved from the cache and `.text`/`.content` is read
2. Cache decoded data
    - (+) No overhead for `.text`/`.content` or `decode_content=True`
    - (+) Backwards compatibility (unless I'm missing something)
    - (-) (Re-)compression is significantly more expensive than decompression
    - (-) Need to implement encoders for the different possible response encodings (deflate, gzip, br)

Realistically I'd consider the usage of raw/encoded responses to be pretty rare, at least in my experience 99.9% of the time the decoded data is used (through `.text`, `.content`, `.iter_content(...)` or `.raw.read(..., decode_content=True)`).

Therefore it might actually be sufficient (for now) to fix the double-decoding that happens with `decode_content=True`, and perhaps log a warning or raise an exception if `decode_content=False` is used explicitly in combination with an encoded response.

**Comment by JWCook** [comment]
Yeah, that sounds like a good compromise. That remaining 0.1% of cases could be a separate issue, if someone really needs it.
