### ISSUE TITLE
option 'include_get_headers' no longer supported?

### ISSUE THREAD

**Issue by MHellmund** [reclosedev/requests-cache#233]
```
cachedSession = requests_cache.CachedSession(expire_after=864000, # 10days 
                                             backend='sqlite',
                                             allowable_methods=('GET','POST'),
                                             old_data_on_error=True, 
                                             include_get_headers=True,
                                             allowable_codes=(200, ))
```

After updating from 0.5.2 to 0.6.2 I get the warning:
`Unrecognized keyword arguments: {'include_get_headers': True}`
Since the option is still in the documentation,  I wonder what to do.

**Comment by JWCook** [comment]
Thanks for pointing this out! That warning shouldn't be happening, but the good news is that this is still working, and you can ignore the warning. Using the `cachedSession` from your example:
```python
>>> cachedSession.get('https://httpbin.org/get', headers={'header': 'value_1'}).from_cache
False
>>> cachedSession.get('https://httpbin.org/get', headers={'header': 'value_1'}).from_cache
True
# Different headers will result in a different cached response
>>> cachedSession.get('https://httpbin.org/get', headers={'header': 'value_2'}).from_cache
False
```

The warning is the result of `include_get_headers` getting passed along to the `BaseStorage` class ([warning here](https://github.com/reclosedev/requests-cache/blob/master/requests_cache/backends/base.py#L173-L174)).

I will get that fixed soon.

**Comment by MHellmund** [comment]
Great! Thank you!

**Comment by JWCook** [comment]
This has been fixed in the master branch, and will be included in the next patch release.
