### ISSUE TITLE
No expiry date on requests and no access/update times in the DB

### ISSUE THREAD

**Issue by iwonbigbro** [reclosedev/requests-cache#24]
Without an expiry date or last access/update time in the DB, I can perform any house keeping.  I have a sqlite DB that is growing infinitely, with void requests being retained forever.  Can we have a column added to the DB that records when the entry was accessed or when it will expire, updating it each time the data is loaded from cache?  I could then setup a house keeping cron to discard invalid request items from the cache.

**Comment by JWCook** [comment]
For reference:
* The SQLite backend now indexes the expiration date for faster cleanup: #364 
* The Redis, MongoDB, and DynamoDB backends support TTL integration: #361 #362 #363 
* Please comment on #116 if a LRU/LFU cache is something you need
