### ISSUE TITLE
Add Readthedocs maintainers

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#241]
Hi @reclosedev, would you be willing to add myself (https://readthedocs.org/profiles/JWCook/) and @skorokithakis (https://readthedocs.org/profiles/stavrosk/) as maintainers for the requests-cache project on Readthedocs?

I would like to add some [automation rules](https://docs.readthedocs.io/en/stable/automation-rules.html) for things like:
* Publishing to `/stable` on git tags, so users don't see in-development changes there
* Making multiple versions of the docs available, so a user can go to, for example, `/v0.5.2` to see docs for the previous version

It would also be convenient for future maintenance if I could do things like manually trigger builds, activate previous versions, etc.

Thanks!

**Comment by reclosedev** [comment]
Hi! Done.

**Comment by JWCook** [comment]
Thank you!
