### ISSUE TITLE
Warning when using option 'ignored_parameters'

### ISSUE THREAD

**Issue by witionstheme** [reclosedev/requests-cache#249]
The following is displayed when using `ignored_parameters` when instantiating `CachedSession` in 0.6.3 since upgrade from 0.5.2.

`Unrecognized keyword arguments: {'ignored_parameters': […]}`

I am assuming it is still working behind the scenes like #233 but a heads up on the warning.

**Comment by JWCook** [comment]
I removed that warning in #237, so that won't show up anymore in the next release. Sorry about that!
