### ISSUE TITLE
Feature request: Add publc api for session.cache._get_valid_responses()

### ISSUE THREAD

**Issue by glensc** [reclosedev/requests-cache#251]
### Use case

Need to inspect cache in human-readable form, to see what it contains.

So, please expose `session.cache._get_valid_responses()` but without delete it should be read-only method, but still skip invalid items.

### Workarounds

Implement userspace, using the private method:
- https://github.com/Taxel/PlexTraktSync/pull/302

**Comment by JWCook** [comment]
Sure, I can add that.

Speaking of human-readable output, I've also been wanting to add a more detailed `CachedResponse.__str__` method to make it a little easier to get general info for cached responses. Let me know if you have any suggestions for that in issue #252.

**Comment by glensc** [comment]
Whilst that would help me, it's not what I've requested here. 

That improves print of individual request, but I'm here asking public method to get such list to walk over.

If you look at the pr I linked, you see I'm using private method. And that private method modifies cache, such side effect must be omitted.

**Comment by JWCook** [comment]
Right, two separate things, that's why I made a separate issue for it.

**Comment by JWCook** [comment]
These changes are in the latest pre-release build. You can test it out with either
```
pip install requests-cache==0.7.0.dev289
```
or
```
pip install -U --pre requests-cache
```

Feel free to create another issue if you run into any problems with that. Also keep in mind pre-release builds are more likely to include bugs. The next stable release will likely be within the next 2 months.

Thanks for the suggestions and feedback!

**Comment by glensc** [comment]
FYI: Updated my project: https://github.com/Taxel/PlexTraktSync/pull/311
