### ISSUE TITLE
Add response details to str(CachedResponse)

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#252]
### Feature description
I'd like to add some more info to the string representation for `CachedResponse`. For `requests.Response`, the default `<Response [status_code]>` is fine, but for cached items, I frequently want to get general information about the response, its original request, and cache expiration.

Possible attributes to include:
* request.method
* request.url
* status_code
* response body size (in human-readable format)
* created_at
* expires
* 'stale' or 'fresh' (based on is_expired)

So the stringified response could look something like:
```python
>>> str(response)
'request: GET https://site.com?foo=bar, response: 200 (24.5 KB), created: 2021-04-04 20:45:00, expires: 2021-14-04 16:45:00 (fresh)'
```

A separate `__repr__` method could return a more verbose list of all attribute key-value pairs, if needed:
```python
>>> repr(response)
'<CachedResponse(method='GET', url='https://site.com', etc.)>'
```

### Use case
This is useful for debugging, unit tests, or just inspecting cache contents in a client application.

### Workarounds
This can be done manually, for example `print(response.request.method, response.url, response.status_code, ...)`, but that can get a bit tedious.

**Comment by glensc** [comment]
Please be sure the date has timezone information, or is converted to local time.

**Comment by JWCook** [comment]
I don't think that will be an issue here, since `created_at` and `expires` are datetime objects in UTC, and formatting a datetime as a string doesn't do any timezone conversion. Usually the problematic part is parsing timezone-naive strings into timezone-aware datetimes. Is that what you're referring to?

**Comment by glensc** [comment]
That's is the problem I'm referring to. You print utc timestamp without timezone info, so user reading it without context will assume it's in local time. It's confusing when you realize that all the hours are off by timezone offset.

So, I asked to include timezone offset (Z, or +0) or convert to local time. 

My preference would be to convert to local time, but the other option will do too.

**Comment by JWCook** [comment]
Okay, I see what you're saying. I'll convert those to local time, and add the timezone name so it's not ambiguous.
