### ISSUE TITLE
Use Poetry for packaging?

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#266]
I'm a fan of [poetry](https://python-poetry.org/), and I'd potentially like to use it for packaging this library if possible.

@jayvdb My main hesitation with this is what you mentioned in #221, regarding poetry making it inconvenient to run tests for downstream packaging. Have you found any good solutions (or compromises) for this in any of the other projects you've worked with?

**Comment by jayvdb** [comment]
Perhaps use poetry for everything except create the sdist with another tool which includes the tests?  Previously I have used @dephell for that, but it is abandoned.

**Comment by JWCook** [comment]
After doing a bit more digging, I think we can make this work by using the `include` option (roughly equivalent to `MANIFEST.in`, if I understand correctly) instead of `packages`. Also, the per-format packages support added in https://github.com/python-poetry/poetry/pull/1133 appears to also apply to `include`, although I don't see that in the docs yet.

Example:
```toml
include = [
    { path = "tests", format = "sdist" }
]
```

I noticed this in poetry's own [pyproject.toml](https://github.com/python-poetry/poetry/blob/master/pyproject.toml), recently updated as a result of https://github.com/python-poetry/poetry/issues/3952.

Here's an example artifact I built using [this config](https://github.com/JWCook/requests-cache/blob/poetry/pyproject.toml):
[requests-cache-0.7.0.dev1.tar.gz](https://github.com/reclosedev/requests-cache/files/6448139/requests-cache-0.7.0.dev1.tar.gz)

That appears to correctly include `tests/` without installing it as a package. Does that look correct to you?

**Comment by jayvdb** [comment]
looks good!

**Comment by JWCook** [comment]
Sweet! I finished and merged these changes to master. The next release will probably be in about a month or two, fyi.
