### ISSUE TITLE
Add option to not store sensitive request info (API keys, etc.) in cached PreparedRequest objects

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#273]
When using a backend that's shared with other services, a user may not want to store certain pieces of request information, like API keys, auth tokens, etc. These could be in either request parameters, headers, or keys in a JSON request body.

We could add a separate option to specify params/keys to not store in the cache. Alternatively, we could add this to the existing behavior of `ignore_parameters`, since the main purpose of that is for things like auth tokens. It may also be worthwhile to make it the default behavior to remove a handful of the most common authentication params & headers, e.g. for OAuth. Either way this would just affect `CachedResponse.request` (a [PreparedRequest](https://docs.python-requests.org/en/master/api/#requests.PreparedRequest) object).

Anyone else have opinions on this?

**Comment by parkerhancock** [comment]
Is this an issue? For all backends, the caching mechanism is to create a secure hash of the request parameters (see requests_cache/cache_keys.py).  As a result, the only thing stored in the backend is an irreversible secure hash of whatever sensitive information was in the request. 

The consequence of this is that whatever secure information was in the request is _irrecoverable_ from the backend, even if the data produced in response to that request could be obtained by querying the backend. But that's related to the security of the _response_, not the request.

As a result, I don't think this is an enhancement that needs to be made. The current architecture protects against recovery of sensitive materials (e.g. API keys, auth tokens, etc) in the _request_ from the backends. And if you want to protect any sensitive information in the _response_, then you can use the other mechanisms to either disable caching to specific endpoints, or disable the cache before sensitive requests.

One related question would be if we want to add encrypted backends to prevent recovery of even the _response_ data, such as adding [SEE](http://www.hwaci.com/sw/sqlite/see.html) or [SQLCipher](https://www.zetetic.net/sqlcipher/) support. But that feels pretty far afield from the basic functionality of this package, and maybe should be left as an exercise for the user.

**Comment by JWCook** [comment]
Thanks for the input! It's probably a small minority of cases where this would potentially be an issue, but credentials sent in the request could still be recoverable if the backend itself isn't secured at all. Besides the hash value used as a `cache_key`, request info is also stored on `response.request`, which is a [`PreparedRequest`](https://docs.python-requests.org/en/master/api/#requests.PreparedRequest) object.

You're right that if you need to secure either your request or response data, using whatever tools are already available for the backend you're using (like the options you linked for SQLite, or just a username/password for the other backends) is going to be the best option. So I guess what this is really about is providing an easier option if you don't want to set up authentication or encryption.

**Comment by parkerhancock** [comment]
Ah! For some reason I didn't realize that. Then yeah! By all means. Seems like a great feature. I suspect it would resemble something like the related feature in [VCRpy](https://vcrpy.readthedocs.io/en/latest/advanced.html#filter-sensitive-data-from-the-request)

Separately - and maybe a separate issue - encryption on backends might be a good idea to the extent that secret key material unlocks secret data in the response. That wouldn't be too hard, since this package already has a good backend base class.

**Comment by parkerhancock** [comment]
FYI - I would love to contribute on this feature. Unless you've already put in some work, let me take a stab at an implementation. 

This library has been fantastic for a number of uses I've put it to, and I'd love to be able to give back!

**Comment by JWCook** [comment]
Yeah, that would be great! Especially if this is something you would potentially use in `patent_client`. I'll add some notes on what I've thought of so far, and let you take it from there.

**Comment by JWCook** [comment]
Here's the general approach I've been trying to take with adding new cache features:
* Add a simple, concise option that covers the majority of basic use cases (preferably via a new or existing keyword arg for `CachedSession`)
* Also allow for more fine-grained control for more complex use cases (and this usage can be more verbose, if needed)
* Try to integrate with existing features when possible

### Request params & body
Looking at the [`ignored_parameters`](https://requests-cache.readthedocs.io/en/v0.6.3/user_guide.html#request-parameters) option would be a good place to start. This already applies to both request params and the request body, since many APIs out there treat these interchangeably, e.g. they let you pass a given parameter either in request params or in a JSON-formatted request body. 

One approach would be to extend the existing `ignored_parameters` option to apply to both cache **keys** and cached **data**, which I think makes sense since the main use case for `ignored_parameters` also happens to be auth tokens.

If you can think of a common enough case where you would want to ignore a parameter when generating cache keys, but include it in the cached response (or vice versa), then adding a separate keyword arg would make more sense.

### Headers
We could add an `ignored_headers` option that works the same as  `ignored_parameters`. So that would also apply to both cache keys (if [`include_get_headers`](https://requests-cache.readthedocs.io/en/v0.6.3/user_guide.html#request-headers) is used) and cached data. I'm open to other suggestions for that, though.

### Advanced usage
For more fine-grained control of what exactly gets cached, I think this would fall under the category of post-processing responses (see #98, for example). That can be done currently with something like:
```python
response = session.get('http://httpbin.org/ip')
response = postprocess(response)
session.cache.save_response(response)
```

But I've seen enough variations of that that I'm considering adding support for a generic hook that takes a `CachedResponse` and does whatever you want to it before saving. That would be a separate issue, though.

**Comment by parkerhancock** [comment]
Hey! I started working on this before your notes, but I think our heads were in the same place. I basically implemented as you suggested (with testing and docs!)

**Comment by JWCook** [comment]
Sweet! I'll take a look soon.

**Comment by JWCook** [comment]
Merged. Thanks for the contribution! Your changes will be available in the latest pre-release build soon.

I think we're good to close this issue for now. Feel free to create a new one if there are more features related to this that you'd like to see.
