### ISSUE TITLE
Monkey patched session giving other requests wrappers heartache

### ISSUE THREAD

**Issue by jharmn** [reclosedev/requests-cache#28]
I detailed this issue on the Rauth repo, which was the specific issue I had. It seems that something with the monkey patching is breaking compatibility with other libraries which leverage requests.
https://github.com/litl/rauth/issues/170

**Comment by JWCook** [comment]
For anyone else's reference, there is a guide to using requests-cache with other requests-based libraries here: https://requests-cache.readthedocs.io/en/latest/user_guide/compatibility.html
