### ISSUE TITLE
How do use Custom Response Filtering and cache based on the response.json()?

### ISSUE THREAD

**Issue by harvey251** [reclosedev/requests-cache#280]
https://requests-cache.readthedocs.io/en/latest/advanced_usage.html#id6

I love this I can't seem to get the custom filtering to work.  I kinda replicated your example, but the response passed into the filter_by_size function is actually a `PreparedRequest` type and doesn't seem to have `response.content` I'm getting `{AttributeError}'PreparedRequest' object has no attribute 'content'`

```
  requests_cache.install_cache('dev_cache',
                                 allowable_methods=('GET', 'HEAD', 'POST'),
                                 allowable_codes=(200, 201),
                                 filter_fn=filter_in_progress
                                 )
```
naively I thought I might be able to do something like check response.json() and decide whether to cache based on that, but now I'm not sure.

**Comment by JWCook** [comment]
> naively I thought I might be able to do something like check response.json() and decide whether to cache based on that, but now I'm not sure.

That's not a naive assumption, that's pretty much exactly what `filter_fn` is supposed to do. This looks like a regression bug. Not sure how that one got past the tests!

Thanks for reporting, I will try to get a patch out for this soon.

**Comment by JWCook** [comment]
@harvey251 Done. Update to `0.6.4` and let me know if that works for you.

**Comment by harvey251** [comment]
Wow that was quick, thank you so much. It's working perfectly

**Comment by JWCook** [comment]
Great! Let me know if you run into any more issues.
