### ISSUE TITLE
Add support and documentation examples for custom serializers

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#283]
Follow-up from #279, and related to #272, #244, and #274. This would be another step toward making requests-cache more extensible. The plan is to distinguish between **serializers** (pickle, json, etc.) and **optional serializer mixins**, which would allow users to add any pre/post-serialization steps. The current cache signing feature (using `itsdangerous`) would fall into this category. The other examples brought up so far are compression and encryption.

A compression mixin using gzip may be worth including in requests-cache, since it's in the standard library and covers the majority of compression use cases.

For encryption, there are several different libraries and algorithms out there, and the best one for the job may depend on the environment. So that may be best left up to the user to decide, with some examples in the docs to help get started. The example from #279 using Fernet encryption from the `cryptography` library would be a good one.

**Comment by parkerhancock** [comment]
I call this one. Is the #275 in close enough to final form to begin, or should I hold off until that's merged?

**Comment by JWCook** [comment]
Thanks! I can't guarantee there won't be merge conflicts, but at this point most of the remaining changes will be in tests, docs, and backend classes, so I think you should be good to start from that branch if you'd like.
