### ISSUE TITLE
 No module named 'requests_cache.response'

### ISSUE THREAD

**Issue by glensc** [reclosedev/requests-cache#296]
Getting such error when upgrading to  0.7.0.dev452 and attempting to call `session.cache.values`:

```
➔ ./plex_trakt_sync.sh cache
Cache status:
redirects: 0
responses: 1499

URLs:
Traceback (most recent call last):
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/./main.py", line 6, in <module>
    cli()
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/.direnv/python-3.9.5/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/.direnv/python-3.9.5/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/.direnv/python-3.9.5/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/.direnv/python-3.9.5/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/.direnv/python-3.9.5/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/plex_trakt_sync/commands/cache.py", line 64, in cache
    for i, r in limit_iterator(sorted, limit):
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/plex_trakt_sync/commands/cache.py", line 33, in limit_iterator
    yield from zip(range(limit), items)
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/plex_trakt_sync/commands/cache.py", line 21, in get_sorted_cache
    yield from sorter(get_responses())
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/.direnv/python-3.9.5/lib/python3.9/site-packages/requests_cache/backends/base.py", line 179, in values
    for _, response in self._get_valid_responses():
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/.direnv/python-3.9.5/lib/python3.9/site-packages/requests_cache/backends/base.py", line 189, in _get_valid_responses
    yield key, self.responses[key]
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/.direnv/python-3.9.5/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 192, in __getitem__
    return self.serializer.loads(super().__getitem__(key))
  File "/Users/glen/scm/plex/Plugins/PlexTraktSync/.direnv/python-3.9.5/lib/python3.9/site-packages/requests_cache/serializers/pickle_serializer.py", line 17, in loads
    return super().loads(pickle.loads(obj))
ModuleNotFoundError: No module named 'requests_cache.response'
```

The code is in this branch:
- https://github.com/Taxel/PlexTraktSync/pull/311

Workaround is to remove cache from previous version, but I rather see the invalid entries being ignored like it was with upgrade to 0.6.0.

**Comment by glensc** [comment]
One thing I noticed as well that the application ran slower 10 times after the upgrade, meaning no cache entries were present usable.

**Comment by JWCook** [comment]
Ah, `ModuleNotFoundError` is a new one, but that makes sense. Thanks for testing. Just pushed a fix for that.

**Comment by JWCook** [comment]
> One thing I noticed as well that the application ran slower 10 times after the upgrade, meaning no cache entries were present usable.

Can you give me an example to reproduce the issue?

**Comment by JWCook** [comment]
Also, I just added some tests that will catch issues similar to this if they come up again in future releases.

**Comment by glensc** [comment]
> > One thing I noticed as well that the application ran slower 10 times after the upgrade, meaning no cache entries were present usable.
> 
> Can you give me an example to reproduce the issue?

Do you still want the example?

but in general, it was like:
1. run app with 0.6.3
2. run app with 0.7.0.dev289
3. run app with 0.7.0.dev452

step 3 was slow. it appeared that 0.7.0.dev452 did not like the previous cache entries

**Comment by JWCook** [comment]
Okay, that should be enough info. I'll look into it.

Thanks again for the feedback and bug reports!

**Comment by glensc** [comment]
Thanks the error is gone with 0.7.0.dev496.

however minor issue, the `responses: 675` is incorrect. it doesn't account for unusable responses. usable responses is actually 0 :)

**Comment by glensc** [comment]
Actually, the cache is in some weird state. I can't dump it, but it seems to be usable by itself.

I think you should be able to reproduce locally:
- update to 0.7.0.dev289, use app
- update to 0.7.0.dev452 or later

iterate over `session.cache.values()` call `str()` on each of them, the `values()` returns empty list.

**Comment by JWCook** [comment]
Hmm, I tried a few times to reproduce that locally, but didn't notice any odd behavior. I'm seeing around 2-3ms per read regardless of previous cache contents, and `session.cache.values()` looks normal.

I'm beginning to suspect my tests using httpbin aren't fully representative, and there may be something in the Plex API responses that requests-cache isn't handling correctly. Could you give me a copy of your cache file created with requests-cache 0.7.0.dev289?

**Comment by glensc** [comment]
I'm confused with the tests as well, so I thought to re-open until the problem is identified clearly.

I thought to run the problematic cache and inspect records with pycharm debugger.

**Comment by glensc** [comment]
1. rm -f cache
2. install requests-cache==0.6.3
3. run app
4. cache dump shows 1 responses and lists 1 response
5. install requests-cache==0.7.0.dev496
6. cache dump shows 1 responses and lists 0 responses
7. run app
8. cache dump shows 2 responses and lists 1 responses

so, after upgrade old entries are inaccessible, they show up in responses count. new entries are created ok and accessible.

hope this helps

**Comment by JWCook** [comment]
Yeah, that helps. So that part is an issue with `BaseCache.__str__()` being misleading, then. It currently just does a simple row count, with no validation.

**Option 1:**
* Update it to count only valid/unexpired responses. The downside is that it will be slightly slower than just doing a row count.

**Option 2:**
* Rephrase it so `str(session.cache)` outputs something like 'total rows' instead of 'responses'
* Add a separate method or property to count only valid responses

Do you have a preference between those two options?

And were you also able to reproduce the slowness you encountered earlier? That's the one I'm still puzzled about.

**Comment by glensc** [comment]
I think option 2, as you already have a method to prune invalid entries.

the slowness came due the fact that older cache entries were not usable, so the cache appeared as empty. ok maybe some time was spent with looking up cache key and finding the cache entry is not usable and then returning 'no cache present'.

**Comment by JWCook** [comment]
I added a method `session.cache.response_count()` and some related changes in #305. Let me know if that works for you!

**Comment by glensc** [comment]
Thanks. I'm not going to update the code for just cosmetics in debugging portion of the application. But thanks anyway.
