### ISSUE TITLE
Can a filesystem backend be included too?

### ISSUE THREAD

**Issue by twneale** [reclosedev/requests-cache#30]
Has anyone else expressed an interested in a basic filesystem backend for cached requests? And is this something you're open to receiving in a pull request?

**Comment by femtotrader** [comment]
I think this could speed up cache usage of https://github.com/pydata/pandas-datareader/issues/153

**Comment by femtotrader** [comment]
[betamax](http://betamax.readthedocs.io/) have something that could probably be considered as a filesystem backend
see http://betamax.readthedocs.io/en/latest/cassettes.html
but I haven't test it

**Comment by codypiersall** [comment]
(Copying and pasting my comment on #109, in case someone here cares)

> I have an implementation for [a project I'm working on](https://github.com/codypiersall/vismap/blob/master/vismap/fs_cache.py).  I have a feeling there are some corner cases I hadn't considered, which is why I'm not submitting a PR.  But maybe this can be a starting point for someone else.

**Comment by JWCook** [comment]
Looks like there was a PR for this submitted a few years ago: https://github.com/reclosedev/requests-cache/pull/97

@twneale If you or someone else would still like this feature, please resubmit that code as a new PR, and I can review and merge it.

**Comment by JWCook** [comment]
If nobody else gets to it before I do, I will likely get this added in the near future. WIP branch here based on the changes linked above: https://github.com/JWCook/requests-cache/tree/filesystem-backend
