### ISSUE TITLE
Unable to modify `CachedResponse` object, raises `AttributeError`

### ISSUE THREAD

**Issue by witionstheme** [reclosedev/requests-cache#320]
### The problem

One of the hooks I run modifies the `Response` object.

Since 0.7 release any hook that attempts to modify the `Response` object -- now returned as `CachedResponse` object -- raises an `AttributeError`.

### Expected behavior

Hooks should be able to modify the `CachedResponse` object.

### Steps to reproduce the behavior

```python
def parse(r, *args, **kwargs):
    if r.status_code == requests.codes.ok:
        r.html = lxml.html.document_fromstring(ftfy.fix_encoding(r.text), base_url=r.url)
        r.html.make_links_absolute()
        return r
```

1. Access uncached resource :)
2. Reaccess resource :(

### Workarounds

None at the moment.

### Environment
- requests-cache version: `0.7.1`
- Python version: `3.9.6`
- Platform: `macOS High Sierra 10.13.6`

**Comment by JWCook** [comment]
You can modify anything that's an attribute on the [Response](https://docs.python-requests.org/en/latest/api/#requests.Response) class, but there's no `html` attribute. That example works with `requests.Response` but not `requests_cache.CachedResponse` because the latter is a slotted class, which doesn't have a `__dict__` and doesn't let you assign new attributes after the class is defined.

One workaround would be to store that in `Response._content`:
```python
def parse(r, *args, **kwargs):
    if r.status_code == requests.codes.ok:
        r._content= lxml.html.document_fromstring(ftfy.fix_encoding(r.text), base_url=r.url)
        r._content.make_links_absolute()
        return r
```

**Comment by JWCook** [comment]
This has been fixed in #324. You can try out the pre-release build with:
```
pip install requests-cache==0.7.2b0
```

Let me know if that works for you, and I'll push out another patch release within a week or so.

**Comment by witionstheme** [comment]
I'll give this a test today, many thanks!

The slotted class would also break caching support for the `requests-HTML` package, they also assign new attributes to the `Response` object.

**Comment by Querela** [comment]
This is nice.
I also kind of subclassed `CachedSession` to attach the cache key to the response. With version `0.7.1` it raised an exception and I had to do a lot more stuff...
(I manually added a table to link cache key to url for easier lookup.)

**Comment by JWCook** [comment]
> I also kind of subclassed CachedSession to attach the cache key to the response. With version 0.7.1 it raised an exception and I had to do a lot more stuff...
(I manually added a table to link cache key to url for easier lookup.)

@Querela Interesting, was that mainly for debugging/development, or for a user-facing feature?

That may be related to some features I'm considering adding in the future, which would involve storing a few response attributes as separate indexed columns to improve certain types of bulk operations. For example, alternative cache eviction methods like #116 would require either `created_at` or `expires` to be a separate column. Having the request URL as a separate column may also be convenient.

I've also considered adding the cache key as a `CachedResponse` attribute. Feel free to make an issue for that, if that's something you would use.

**Comment by Querela** [comment]
It was kind of for both. As the dev myself it was mostly for debugging purposes for now, e. g. checking what URLs are cached, possibly cleaning up cache entries from previous requests, ...

My situation: I had to crawl/scrape a large amount of URLs. Unfortunately the cache file only includes the cache-key which I was not able to inversely map to the request URL if it is not stored beforehand.
I intend to later just check by cache key whether I have a stored response without requesting again. It is not strictly neccessary but allows me to use the URLs to retrieve the responses without simulating my whole scraping process. (And for me, only the URL changes between each request, so my lookup is essentially 1:1).

The code I had to use to attach the URLs to my cache keys. I simulate the crawling/scraping to retrieve the cached responses, and then just compute the cache keys. (I could do this while I do my actual crawling but this came afterwards.)
```python
import json
from os import PathLike
from pathlib import Path
from typing import Iterator
from urllib.parse import urljoin

import requests
from parsel import Selector
from requests_cache import CachedSession
from requests_cache.backends.sqlite import DbDict

REQ_HEADERS = {
    "User-Agent": "...",
}
REQ_COOKIES = {}


# subclass cached session to retrieve the key (response here not required)
class MyCacheKeySession(CachedSession):
    def send(self, request, **kwargs):
        return self.cache.create_key(request, **kwargs)
        # NOTE: the code below failed
        # response = super().send(request, **kwargs)
        # setattr(response, "cache_key", self.cache.create_key(request, **kwargs))
        # return response


# simulate the crawling / scraping process
def iter_serieslists_urls(sess: requests.Session) -> Iterator[str]:
    url = "https://the.start.url/series/"

    while True:
        yield url

        resp = sess.get(url)
        assert getattr(resp, "from_cache", False)

        sel = Selector(resp.text)
        next_url = sel.css("div.pagination a.next_page::attr(href)").get()
        if not next_url:
            break

        url = urljoin(url, next_url)


def get_session(
    cache_file: str = ".cache.sqlite",
    allowable_codes=(200,),
    session_cls=CachedSession,
    **kwargs
) -> requests.Session:
    backend = DbCache(cache_file)
    session = session_cls(backend=backend, allowable_codes=allowable_codes)

    if "headers" in kwargs:
        headers = kwargs["headers"]
    else:
        headers = REQ_HEADERS
    if headers:
        session.headers.update(headers)

    if "cookies" in kwargs:
        cookies = kwargs["cookies"]
    else:
        cookies = REQ_COOKIES
    if cookies:
        requests.utils.add_dict_to_cookiejar(session.cookies, REQ_COOKIES)

    return session


def main():
    cache_file = ".cache.sqlite"
    session_kwargs = dict(cache_file=cache_file, allowable_codes=(200, 302))
    sess = get_session(**session_kwargs)
    fakesess = get_session(**session_kwargs, session_cls=MyCacheKeySession)
    cache_url_table = DbDict(cache_file, table_name="key2url")

    url_iter = iter_serieslists_urls(sess)  # crawling simulator, returns the request urls
    for url in url_iter:
        key = fakesess.get(url)  # to get the cache key
        cache_url_table[key] = url  # store url for key
```
I could solve this differently but it works for me now.

Having the cache key as a attribute would be nice.
But I would make storing the URL in the cache optional. My last crawl had 10k or more? responses and my cache file is 4GB large. Just the URLs are probably only ~5MB but including more metadata if they are not required/used might increase the filesize again. Maybe including an empty hook that allows users to subclass the CachedSession to store arbitrary JSON strings or pickled data for a given cache-key?

**Comment by JWCook** [comment]
Thanks for the details, that's helpful. And yes, additional cache columns would definitely be optional, and I like the idea of leaving it up to the user which columns to include. That may be part of the next release (`0.8`).

> I "abuse" the cache as a kind of web-archive

That's a cool idea! I've seen other users do something similar. Let me know if you have more ideas for features that would be useful for the "pseudo-web-archive" use case.

**Comment by JWCook** [comment]
Also, the fix for this issue (as well as the new `CachedResponse.cache_key` attribute) is now in the latest stable release (`0.7.2`).

I'm going to go ahead and close this issue, but you're welcome to create more if you have any more problems or feature requests.

**Comment by Querela** [comment]
Just asking here, I will create an extra issue if necessary: Can I kind of simulate the requests? As in, if the response is cached, return the response if nothing is cached, raise an exception? That would be like monkeypatching in tests to block outgoing requests. This would make working with the pseudo web archive easier as for now (?) there is no mapping for the URL stored and we still need to do the detour over the request.

The call-flow currently is:
`CachedSession.get(some_url)` (which is `Session.get()`) &rarr; `CachedSession.request()` &rarr; `Session.request()` &rarr; `CachedSession.send()` &rarr; (...) `CachedSession._send_and_cache()` &rarr; `Session.send()` (which calls the `http[s]` adapter `HTTPAdapter` that does the actual sending via `urllib3`)

So would I override the `http[s]` adapter in `Session.adapters` or _better_ subclass `CachedSession._send_and_cache` and just raise an exception?
I'm not sure how many would want to _simulate_ the requests with an existing cache, to justify another parameter and check in the code? It could alternatively implemented with an additional attribute/flag (`_send_disabled`) and with `send_disabled` (see `cache_disabled`) context handler.

**Comment by Querela** [comment]
Hm. The new version does not allow to unpickle from the older class definitions. I have to look whether I can kind of convert my older cache to the newest version.

**Comment by JWCook** [comment]
Good question! I would be okay with adding another parameter for this. The problem with subclassing is that it might break with future releases, since internal methods like `_send_and_cache()` are likely to change. You could pin your dependencies by minor version (`requests-cache~=0.7.2` or `requests-cache<0.8`) to avoid that, if needed. Adapters are a good approach, but maybe a bit more code. Also see this example of [combining requests-cache with requests-mock](https://requests-cache.readthedocs.io/en/v0.7.2/advanced_usage.html#requests-mock), which may do what you want.

Let's continue this in a separate issue to make it easier for others to find: #330

**Comment by JWCook** [comment]
> Hm. The new version does not allow to unpickle from the older class definitions. I have to look whether I can kind of convert my older cache to the newest version.

Yes, unfortunately this will happen any time we pickle a non-builtin type (like `CachedResponse`), and then add or modify attributes on that type. There are some notes on that in the [changelog here](https://github.com/reclosedev/requests-cache/blob/master/HISTORY.md#serialization-1). I previously added a script to convert an existing cache from `0.5` to `0.6`, but not from `0.6` to `0.7`. I can probably look into that either later this week or next week if you don't figure it our first.

**Comment by JWCook** [comment]
The `0.7` update also added a way to make your cache more future-compatible: if you `pip install cattrs`, then requests-cache will use that to 'unstructure' responses so they will be pickled as builtin types instead of `CachedSession` objects. This is not yet the default behavior and isn't fully documented, since it requires python 3.7+, and requests-cache still supports python 3.6  (which will be dropped in a future release).

This is done in [serializers/cattrs.py](https://github.com/reclosedev/requests-cache/blob/master/requests_cache/serializers/cattrs.py) and [serializers/preconf.py](https://github.com/reclosedev/requests-cache/blob/master/requests_cache/serializers/preconf.py), if you're curious.

**Comment by Querela** [comment]
Ok. I will look into it. :-)
I found the json storage option (which uses the mentioned `cattrs`). And here some quick testing indicated that saving in 0.7.1 and loading in 0.7.2 works. But I used the filesystem cache instead of sqlite.

**Comment by Querela** [comment]
Ok. I found a simple way to update the stored responses. But it depends on the availability of `cattrs`.
Essentially, install `cattrs` so the default `pickle_serializer` uses it. Then load and store each response. This makes them use just the basic python types with robust default values for newly introduced attributes. Then upgrade to newer version.
_Python 3.6 is EOL in ~5 month. Most with current systems (non LTS servers) will probably be on python 3.8 or 3.9. So a conversion script might be nice but not really necessary?_

Code:
```python
from requests_cache.backends.sqlite import DbPickleDict
# assumes default names from the DbCache, with db_path being the cache filename
# serializer=pickle_serializer (is default, uses cattrs if installed)
dpd = DbPickleDict(db_path=".cache.sqlite", table_name="responses", use_temp=False, fast_save=False)
for key in dpd:
    dpd[key] = dpd[key]
```

**Comment by JWCook** [comment]
@Querela Nice! I'm glad there was a simple way to do that.

**Comment by Querela** [comment]
Well, for me. As you said, `cattrs` is still optional and does not support python 3.6. So some might not be able to use this. But otherwise this is enough and seems future proof. And an easier way is impossible.
You thankfully pointed me in the right direction. 😄
