### ISSUE TITLE
✨ Add support for ETag and Last-Modified headers

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#332]
Support for basic `Cache-Control` headers was added with #192 / #261. For more complete header support, the next logical step would be handling `ETag` and `Last-Modified` headers.

Here is an outline of how I would expect that to work:
* When a cached response is retrieved and it's expired:
    * If it contains an `ETag` header, add an `If-None-Match` header to the request
    * If it contains a `Last-Modified` header, add an `If-Modified-Since` header to the request
    * If a  `304 Not Modified` response is received, returned the cached response
    * If a new `200` response is received, update the cache and return the new response

Other related headers to consider:
* `If-Match`
* `If-Unmodified-Since`
* `If-Range`

I'm unsure if/how those should be used within requests-cache, though.

If this is a feature you would like, please comment!

**Comment by JWCook** [comment]
@cybershadow
I would consider also adding support for  `Last-Modified` + `If-Modified-Since`. If a site (like the GitHub API) provides both `ETag` and  `Last-Modified`, would it make sense for the `ETag` to take priority?

In other words:
* Use `Cache-Control` to set initial expiration, if provided
* Return the cached response until it expires, as usual
* When it expires:
    * If there's an `ETag`, send a `If-None-Match` request and return the cached response if we get a 304
    * If there's a `Last-Modified`, send a `If-Modified-Since` request and return the cached response if we get a 304
    * Otherwise fetch and return a new response

Does that look correct to you?

**Comment by JWCook** [comment]
Also, are you aware of any use cases for `If-Match` and `If-Unmodified-Since` that would make sense to handle in requests-cache?

**Comment by CyberShadow** [comment]
> Does that look correct to you?

I believe there is no harm in including both `If-None-Match` and `If-Modified-Since` in the same request, at least as far as I'm aware in theory (HTTP spec) and in practice ([with GitHub in particular](https://github.com/CyberShadow/ae/blob/3ddbf59cf4e6bea3a59d132ad813773b1ea8dcdc/net/github/rest.d#L77-L80)).

> If a site (like the GitHub API) provides both ETag and Last-Modified, would it make sense for the ETag to take priority?

I'm actually aware of one anecdote in favor of this:  [For some requests, GitHub may reply with a "304 Not Modified" even when some parts of the request have changed since the date in the "If-Modified-Since" header.](https://github.com/milo/github-api/pull/24) This does not apply to `ETag` + `If-None-Match`, so if for whatever reason only one header would be sent, `ETag` seems preferable.

> Also, are you aware of any use cases for `If-Match` and `If-Unmodified-Since` that would make sense to handle in requests-cache?

None that I'm aware of.

**Comment by JWCook** [comment]
Thanks, that's helpful! I'll plan on sending both request headers if they're both available, then.

Would you be willing to help test this out when it's finished?

**Comment by CyberShadow** [comment]
Sure, I'll give it a spin :)

**Comment by JWCook** [comment]
Changes for this are in the latest pre-release build (`0.8.0.dev0`).

**Comment by CyberShadow** [comment]
Yes, it seems to work!

For the record, here is the code I am using to test:

```python
import time

import requests_cache
requests_cache.install_cache(cache_control=True)

import github
gh = github.Github()

gh.get_user("GitHub")
a = gh.rate_limiting
gh.get_user("GitHub")
b = gh.rate_limiting
time.sleep(61)  # Ensure max-age passes
gh.get_user("GitHub")
c = gh.rate_limiting
print(a[0] - c[0])
```

Also for the record, here is one very intrusive method I found to achieve the same using the cachecontrol package:
```python
from cachecontrol import CacheControl
from cachecontrol.caches import FileCache

# Patch in cache support for PyGithub
class CachingConnectionClass(gh._Github__requester._Requester__connectionClass):
    def __init__(self, *args, **kwargs):
        super(gh._Github__requester._Requester__connectionClass, self).__init__(*args, **kwargs)
        self.session = CacheControl(self.session,
                                    cache=FileCache('.github-cache'))
gh._Github__requester._Requester__connectionClass = CachingConnectionClass
```

**Comment by JWCook** [comment]
Great, thanks for confirming!

And that example is interesting, because it looks like the same approach would be needed if you wanted to use PyGithub with [`requests_cache.CachedSession`](https://requests-cache.readthedocs.io/en/stable/user_guide.html#sessions). If for example you were using PyGithub + requests-cache in a library that would be imported by other projects (as opposed to a standalone application), you might not want to use `requests_cache.install_cache()` since it would also affect any requests in downstream projects.

One compromise I can think of would be to add an option like `install_cache(target='some_module')` that would let you do a more targeted patch for [`github.Requester.requests.Session`](https://github.com/PyGithub/PyGithub/blob/83d6e0719cb7bfee57af398f93a73516b62af5f2/github/Requester.py#L99) instead of `requests.Session`.
