### ISSUE TITLE
Feature request: bulk_delete_urls

### ISSUE THREAD

**Issue by Avasam** [reclosedev/requests-cache#336]
### Use case
_Is there a specific goal that this would help you accomplish, or can you provide any other context about how you would like to use this feature?_
```py
def clear_cache_for_user_async(userId: str):
    def clear_cache_thread():
        try:
            print(f"Looking for cache specific to user '{userId}'...")
            user_cached_urls = [url for url in session.cache.urls if userId in url]
            print("user_cached_urls:", user_cached_urls)
            session.cache.bulk_delete_urls(user_cached_urls)
        except Exception:
            print(f"Something went wrong while deleting cache for '{userId}'")
            raise
    Thread(target=clear_cache_thread).start()
```
I'll want to clear some of my cached requests once some work was finally able to complete to keep the database size low (I found SQLite tends to slow down when it hits a few hundred MBs). But keep other requests (which are shared across different workloads). For this I filter the requests I want to remove, and bulk remove them.

### Workarounds
_Is there an existing workaround to accomplish this?_
The following locks up:
```py
print(f"Looking for cache specific to user '{userId}'...")
print("user_cached_urls:")
print(list(session.cache.keys()))
for url in session.cache.urls:
    if userId not in url:
        continue
    print(url)
    session.cache.delete_url(url)
```
<details>

```py
Something went wrong while deleting cache for '18q6g70j'
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Avasam\Documents\Git\speedrun.com_global_leaderboard_webapp\services\utils.py", line 110, in clear_cache_thread      
    session.cache.delete_url(url)
  File "C:\Program Files\Python37\Lib\site-packages\requests_cache\backends\base.py", line 108, in delete_url
    self.delete(url_to_key(url, self.ignored_parameters))
  File "C:\Program Files\Python37\Lib\site-packages\requests_cache\backends\base.py", line 102, in delete
    del cache[key]
  File "C:\Program Files\Python37\Lib\site-packages\requests_cache\backends\sqlite.py", line 128, in __delitem__
    cur = con.execute(f'DELETE FROM {self.table_name} WHERE key=?', (key,))
  File "C:\Program Files\Python37\lib\contextlib.py", line 119, in 
__exit__
    next(self.gen)
  File "C:\Program Files\Python37\Lib\site-packages\requests_cache\backends\sqlite.py", line 99, in connection
    self._local_context.con.commit()
sqlite3.OperationalError: database is locked
```
</details>

Looking deep in the docs I found I could do this which seems to work:
```py
session.cache.bulk_delete(
    [url_to_key(url, session.cache.ignored_parameters)
        for url in session.cache.urls
        if userId in url])
```

### Plan to implement
_Are you interested in submitting a PR to implement this?_
I was gonna say no, but the final solution that I found is quite easy to implement. I might if you approve.

**Comment by JWCook** [comment]
`bulk_delete` is exactly what I was about to recommend. It would be easy enough to wrap that in a `BaseCache.delete_urls()` method. I can get that added soon.

Another option to consider: if the responses you're clearing are all cached by a specific function, you could use a separate cache file for that function and then `session.cache.clear()` the whole thing when you're done.

**Comment by Avasam** [comment]
> Another option to consider: if the responses you're clearing are all cached by a specific function, you could use a separate cache file for that function and then `session.cache.clear()` the whole thing when you're done.

Good idea, I'll consider this, thank you!
