### ISSUE TITLE
expire_after parameter should also accept datetime.timedelta

### ISSUE THREAD

**Issue by femtotrader** [reclosedev/requests-cache#35]
Hello,

it will be nice if `expire_after` parameter could also accept `datetime.timedelta`
(instead of seconds).

    import requests
    import requests_cache
    import datetime
    requests_cache.install_cache('cache', backend='sqlite', expire_after=datetime.timedelta(hours=1))
    request.get('http://www.google.fr')
    request.get('http://www.google.fr')

You should modify `core.py`

        if self._cache_expire_after is not None:
            difference = datetime.utcnow() - timestamp
            if difference > timedelta(seconds=self._cache_expire_after):
                self.cache.delete(cache_key)
                return send_request_and_cache_response()

to

        if self._cache_expire_after is not None:
            difference = datetime.utcnow() - timestamp
            if difference > self._cache_expire_after:
                self.cache.delete(cache_key)
                return send_request_and_cache_response()

assuming (that `self._cache_expire_after` is a `timedelta`)

and 

    class CachedSession(OriginalSession):
        def __init__(self, ...):
            ...
            self._cache_expire_after = expire_after
            ...

to

    class CachedSession(OriginalSession):
        def __init__(self, ...):
            ...
            try:
                self._cache_expire_after = timedelta(seconds=expire_after)
            except:
                self._cache_expire_after = expire_after
            ...

Kind regards

**Comment by femtotrader** [comment]
Hello,

it will be nice if you could push this feature on Pypi.

Kind regards

**Comment by reclosedev** [comment]
Sorry for delay. New version is on PyPI now.

**Comment by femtotrader** [comment]
Thanks again
