### ISSUE TITLE
Add TTL support for Redis backend

### ISSUE THREAD

**Issue by JWCook** [reclosedev/requests-cache#361]
Redis supports expiring cache items automatically with [TTL](https://redis.io/commands/TTL), and even updating an existing expiry with the [EXPIRE](https://redis.io/commands/expire) command. This would be a much more efficient means of clearing expired cache items.

Currently, expired cache items are only removed/updated when they are next requested, filtered out with [filter_fn](https://requests-cache.readthedocs.io/en/stable/advanced_usage.html#custom-response-filtering), or when [remove_expired_responses()](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.html#requests_cache.backends.base.BaseCache.remove_expired_responses) is manually called (which is fairly inefficient for large caches).

Note that this will require some changes to store items under top-level keys instead of in a single hash, since TTL is not supported for individual hash fields.

**If you use requests-cache with Redis and this is a feature you would like, please comment!**

**Comment by MonsieurV** [comment]
Yes, would be great!

I was considering some time ago do a try at it (but not sure when I could work on it).

**Comment by JWCook** [comment]
Changes are now in the latest pre-release build.
