### ISSUE TITLE
Add __repr__ (and/or __str__) method

### ISSUE THREAD

**Issue by femtotrader** [reclosedev/requests-cache#39]
Hello,

it will be nice to provide a `__repr__` (and/or `__str__`) method (at least for `CachedSession`)
for example it should display expire_after, backend, cache_name in a "human" way.

it will help when dealing with requests-cache in IPython notebooks

Kind regards

**Comment by reclosedev** [comment]
Added following representation
```
<CachedSession(DbCache('requests_cache_test', ...), expire_after=0:00:10, allowable_methods=('GET',))>
```
Feel free to improve it with PR

**Comment by femtotrader** [comment]
Thanks
