### ISSUE TITLE
Why does the debug log message read "Skipping cache write for URL" when the URL is being cached?

### ISSUE THREAD

**Issue by jonasjancarik** [reclosedev/requests-cache#408]
It could be just me but I don't find the message produced here very intuitive: https://github.com/reclosedev/requests-cache/blob/ae95d6d96340fde8d65ed0c5c820f0be87d25346/requests_cache/session.py#L182

Obviously maybe I am reading it wrong or perhaps I misunderstood some basic concept here.

**Comment by JWCook** [comment]
And since logging is one of the only things not covered by unit tests, any other feedback you have on logging would be helpful, or any suggestions for things that aren't being logged but should be.

**Comment by jonasjancarik** [comment]
Ok, I've only just now started using logging with requests-cache but I'll
keep an eye out. Thanks for fixing this so quickly!
