### ISSUE TITLE
`ignored_parameters` leaks private information via serialized responses

### ISSUE THREAD

**Issue by RodericDay** [reclosedev/requests-cache#409]
### The problem
We have some private tokens for API calls, and these private tokens end up cached regardless of what back-end we utilize, because, although the `response.request.url` is cleaned-up, the secret is still present in the string attribute `response.url`.

### Expected behavior
I expect, if a certain URL param is ignored, for it to be ignored both in the `request` *and* in the `response`.

### Steps to reproduce the behavior
1. Install the cache to intercept all requests with backend to `filesystem` and the serializer to `json`, and provide `ignored_parameters=[<secret>]`.
2. Make a request with a "secret" token.
3. Look at cached response file, it will have removed the secret from `request.url`, but it still exists on the top-level `url`.

### Workarounds
Hacking the code like this stops the secret from appearing in the cache files (`/backends/base.py`):
![image](https://user-images.githubusercontent.com/6867226/133468614-ed533872-2035-4bc3-b421-564b461619b8.png)

### Environment
- requests-cache version: `0.8.0`
- Python version: `3.9`
- Platform: `OSX`

**Comment by JWCook** [comment]
Thanks for reporting this! I'll get that fixed shortly.

**Comment by JWCook** [comment]
This has been fixed in v0.8.1, and also backported to v0.7.5 for python 3.6 compatibility.

A somewhat related issue is #388, so any feedback on that would be appreciated.
