### ISSUE TITLE
Use a spdx license for license= in pyproject.toml

### ISSUE THREAD

**Issue by FredHappyface** [reclosedev/requests-cache#427]
### The problem
Pypi.org lists an incorrect license (likely caused by poetry generating an incorrect classifier from your license)

### Expected behavior
License classifier is "OSI Approved/BSD License"

### Steps to reproduce the behavior
Navigate to https://pypi.org/project/requests-cache/ license classifier is "Other/Proprietary License"

### Fix

Per https://python-poetry.org/docs/pyproject/#license

use `license="BSD-2-Clause"`  (https://spdx.org/licenses/BSD-2-Clause.html)

### Environment
- requests-cache version: 0.8.1
- Python version: 3.9
- Platform: Windows 10

**Comment by JWCook** [comment]
Thanks for pointing that out! You're right, it looks like this happened after switching to poetry for v0.7 (in PR #267).

This is fixed now, and the next release will show the correct license on PyPI.

**Comment by JWCook** [comment]
Just tested this out with a pre-release build: https://pypi.org/project/requests-cache/0.8.2dev1
