### ISSUE TITLE
backend parameters passed to session are being ignored if Backend instance is also provided to the session

### ISSUE THREAD

**Issue by Iftahh** [reclosedev/requests-cache#442]
### The problem
The docs describe `ignored_parameters` like [this](https://requests-cache.readthedocs.io/en/stable/user_guide/matching.html#selective-parameter-matching)
```python
session = CachedSession(ignored_parameters=['auth-token'])
```

and they also describe passing a custom backend by instnace like [this](https://requests-cache.readthedocs.io/en/stable/user_guide/backends.html)
```python
backend = RedisCache(host='192.168.1.63', port=6379)
session = CachedSession('my_cache', backend=backend)
```

However these two are incompatible, since the ignored_parameters are actually not a session variable, but a backend variable and the session only passes these values to the backend if the backend is constructed by the session  (that was a mouthful... I hope I am clear).  If the instance of the backend is passed to the session, then the `ignored_parameters` is being silently ignored.  This is confusing, and since it doesn't raise an exception or log an error, and everything works (except the parameters are not ignored...) it is very easy to miss.

Note this is probably true for other backend parameters, but this "ignored_parameters" affected me and I haven't checked the others.

### Expected behavior
1. Do not silently ignore the backend parameters,  if a backend instance is passed and also backend parameters are passed to the session then raise an exception.
2. Fix the session documentation and preferably also the function parameters so that is extra clear, something like passing "backend_parameters" will make it clearer

```python
# this is fine - the backend_parameters are passed when the backend is constructed inside
session = CachedSession('my_cache',  backend_parameters={"ignored_parameters": ["secret_token"]}))

# should raise exception that the backend parameters are not used
session = CachedSession('my_cache',  backend=my_backend_instance,  backend_parameters={"ignored_parameters": ["secret_token"]}))

```

### Workarounds
Yes,  the user who constructs the backend can pass the parameters there and not to the session.

**Comment by JWCook** [comment]
> While this would work for the ignored_parameters param, it is skipping the work done in the constructor,
so passing include_get_headers or cache_name will not be set to their correct instance variables (match_headers and name, respectively)

One way around that would be to handle the deprecated `include_get_headers` kwarg via a property, and change `BaseCache.name` to `BaseCache.cache_name`. If that sounds reasonable to you, here's a PR for that: #447

**Comment by JWCook** [comment]
I'll close this for now since I think that PR mostly address the issue, but you're welcome to open another issue if you have more ideas or suggestions. Thanks!
