### ISSUE TITLE
Add section to docs summarizing performance considerations

### ISSUE THREAD

**Issue by sandrotosi** [reclosedev/requests-cache#459]
Hello,
while reading the [doc](https://requests-cache.readthedocs.io/en/stable/user_guide/backends.html) about backends, there's no mention about performance considerations (and/or benchmark results).

F.e., some of the information i think would be able to have are:

* which backend is best for just a few requests to a small number of URLs? (ok, i expect all of them to be good, but seeing some numbers would be good)
* what if there are millions of requests to just a handful of URLs?
* what if there are a handful of requests against a cache with millions entries?
* what if there are millions of requests against a cache with millions of entries?
* what's the disk/memory overhead of each backend?

thanks,
Sandro

**Comment by JWCook** [comment]
Good questions! You're right, it might be worthwhile to have a separate section in the docs for performance tips. Do you have a specific use case in mind, or is this more of a general suggestion for the docs?

The docs for some of the individual [backend classes](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.html) have a bit of info on what kinds of use cases each one is good for, and a few notes on performance. Also see [examples/benchmark.py](https://github.com/reclosedev/requests-cache/blob/master/examples/benchmark.py); if you're interested, you can tweak those settings and see for yourself how each backend performs. See the [Testing Backends](https://requests-cache.readthedocs.io/en/stable/user_guide/backends.html#testing-backends) section for details on running backend containers for local testing.

The short answer:
* SQLite is going to give you the best all-around performance for most cases, until you have a specific reason to switch. You can expect sub-millisecond response times even for a very large cache.
* If/when you outgrow SQLite (typically for a large distributed application), the next logical choice would usually be Redis.
* In most cases, all of the backends perform well enough that they won't be a bottleneck until you start hitting about 1000+ requests per second.

Usually your choice of backend will depend not so much on the number of requests, cache size, etc., but more on the environment your application is running in and how much concurrency (if any) is involved. Situations where you would want to choose one of the other backends include:
* You have a distributed application running across multiple machines
* You are going to be making a lot of concurrent writes (i.e., many nodes/threads/processes and many different URLs)
* Your application is running in an environment with little to no local storage (like some cloud computing services)
* Your application is already storing other data in one of the other backends
* You want to use a specific feature available in one of the backends
* You want your cached request data to be stored in easily human-readable or reusable files (filesystem backend)

**Comment by JWCook** [comment]
That will probably answer most of your questions, but for the specific scenarios you mentioned:
* Few requests, few URLs: Any of the backends, really, but usually SQLite
* Many requests, few URLs: You'll be doing just a few writes followed by lots of reads, so SQLite will be perfect. Assuming you have a modern SSD, its read performance is the fastest, next to (non-persistent) in-memory caching.
* Large cache: Almost all of the backends scale well and should perform just fine with millions of entries.
    * The only exception might be the filesystem backend, since it doesn't currently implement fanout. That's a possible future improvement, though.
    * See [examples/generate_test_db.py](https://github.com/reclosedev/requests-cache/blob/master/examples/generate_test_db.py) to simulate the conditions you want to test against.
* Disk/memory overhead: I'm not sure, but I'll run some tests later and get back to you.
    * My hunch, though, is if your application is running in a memory-constrained environment, you'll want to use SQLite or filesystem.
    * SQLite will probably be more disk space efficient than filesystem (how much more depends on serializer settings)
    * If the environment also has slow or limited local storage, you'll want to connect to a backend server running on a different machine.
    * This isn't applicable to DynamoDB. Since its a fully managed service on AWS, you don't know or care about the hardware resources it uses, you just pay based on how much you use it.
    * Redis will probably be the most memory-intensive.

**Comment by JWCook** [comment]
@sandrotosi Does that answer your questions?

**Comment by sandrotosi** [comment]
thanks, yes it does! I'm wondering if you're going to add a section to the doc to cover performance?

**Comment by JWCook** [comment]
Yes, I'll add a section to the docs with at least a brief summary of performance info. I probably won't be able to go into too much more detail than what I outlined above, though, since it depends so much on the application's usage pattern.

I'll leave this issue open until I add that. PRs for doc updates are also welcome!

**Comment by sandrotosi** [comment]
fantastic change, that's very informative and exactly what i needed -- thanks!

**Comment by JWCook** [comment]
Good! By the way, you can preview this in the pre-release docs here: https://requests-cache.readthedocs.io/en/latest/user_guide/backends.html
