### ISSUE TITLE
Cache images

### ISSUE THREAD

**Issue by socketubs** [reclosedev/requests-cache#46]
Hi,

Is it ok to cache requests that return images ?
Or sqlite will just explose when it will have 50k cached requests ?

Thanks.

**Comment by reclosedev** [comment]
Hi,

I didn't try this. It probably will take more time, memory (if images is big) and more disk space, but should work fine.
Also, depends on what will you do with these images, maybe it's better to avoid saving it to cache.

**Comment by socketubs** [comment]
I want to cache requests that only return images... Maybe doing my own implementation could be better. I doubt in sqlite to cache images. This is not really its job :smile:

**Comment by reclosedev** [comment]
If you'll cache only images then own implementation will be better. And the reason is not only SQLite, but overhead of storing pickled responses in it.

**Comment by socketubs** [comment]
We can close this issue which is not an issue. :smile:
