### ISSUE TITLE
testing redis and mongo

### ISSUE THREAD

**Issue by sandrotosi** [reclosedev/requests-cache#47]
Hi,
it seems the tests for redis and mongo just try to access those 2 application on their default address/port (as no specific connection is specified nor it's possible to do so). I think the best way is to create and ad-hoc instance for both redis and mongo (just for the tests) and destroy it right after they are finished - what do you think?

**Comment by reclosedev** [comment]
Hi,
Default address/port is ok for travis CI.

It's possible to pass redis/mongo connection instance to cache, and it's easy to add it to tests, (e.g. with params from environment).

>create and ad-hoc instance for both redis and mongo (just for the tests) and destroy it right after they are finished
Do you you mean launching mongod/redis-server? Maybe some docker image would be better.

**Comment by sandrotosi** [comment]
Hi,
ok it works for travis, but I'm aiming to a more general solution, which is yes, launching mongo/redis server instances from the tests (which creates a self-contained test environment where tests run: 1. spawn a new (temporary) db instance; 2. use if for tests; 3. destroy that temporary instance) but adding a docker image is definitely overkill here

**Comment by reclosedev** [comment]
Writing (testing and supporting) code to support launching/destroying different types of db instances don't seems more general for me.

I've seen project (enterprise) which creates DB server in ``setUp`` and destroys it in ``tearDown``. There was so much pain with it, also it's very slow.

**Comment by JWCook** [comment]
For reference, integration test services are now managed with Docker and docker-compose: https://github.com/reclosedev/requests-cache/blob/master/CONTRIBUTING.md#integration-test-containers
