### ISSUE TITLE
Feature request: convenience function for getting cache entries from CachedSession

### ISSUE THREAD

**Issue by riklopfer** [reclosedev/requests-cache#478]
### Feature description

Simple function to get cached response if it exists. 

Method signature on CachedSession would be something like, 

```python
def get_cached(self, method: str, url: str, **params) -> Optional[CachedRequest]:
    # form Request, add params from Session, get from cache
```

### Use case

* one case would be where you need to do an auth request before doing another request which may or maybe not already be cached. This way we can avoid doing the call to get the auth token if the second request is already cached. 

### Workarounds

Do the same thing in client code. 

### Plan to implement

Willing to add a PR if needed

**Comment by JWCook** [comment]
I believe #394 would do what you want. Once implemented, you could do what you described with something like:
```python
response = session.get(url, only_if_cached=True)
if response.status == 504:
    response = session.get(url, auth=get_auth_token())
```

**Comment by riklopfer** [comment]
That'll work. Thanks! Maybe this usage could be better documented though.

**Comment by JWCook** [comment]
That issue hasn't been done yet, but I'll add it to the docs when I get to it. I'll try to fit this into the next release.

**Comment by JWCook** [comment]
The `only_if_cached` option is now available in the latest pre-release build, and is documented here: https://requests-cache.readthedocs.io/en/latest/user_guide/expiration.html#cache-only-requests
