### ISSUE TITLE
test suite leaves temp cache file behind

### ISSUE THREAD

**Issue by sandrotosi** [reclosedev/requests-cache#48]
Hi,
after running the test suite, the file requests_cache_test.sqlite is not deleted

**Comment by femtotrader** [comment]
A context manager could be a good idea. 

See for example https://github.com/pydata/pandas/blob/master/pandas/util/testing.py `ensure_clean`

and its usage for example in https://github.com/pydata/pandas/blob/master/pandas/io/tests/test_excel.py

see also http://stackoverflow.com/questions/13379742/right-way-to-clean-up-a-temporary-folder-in-python-class
