### ISSUE TITLE
Apply expired_after both to existing cached response and to new cached response

### ISSUE THREAD

**Issue by char101** [reclosedev/requests-cache#481]
Hi,

If I initially do not set any expiration then the response will not expire in cache. Now if I set `expired_after` the response returned will always be the cached response, even though the cached response is created beyond the `expired_after` interval.

If I set `expire_after=300` wouldn't it mean that:

1. I want any new response to be cached for 300 seconds
2. But I also only want any cached response that is created within 300 seconds before this request

Is this kind of behavior possible with the current API?

**Comment by JWCook** [comment]
You can set a new expiration for the entire cache using the `expire_after` param for [`CachedSession.remove_expired_responses()`](https://requests-cache.readthedocs.io/en/stable/session.html#requests_cache.session.CachedSession.remove_expired_responses).

Will that accomplish what you want?

**Comment by char101** [comment]
Following the function call `CachedSession.remove_expired_responses()` uses the function `get_expiration_datetime()` to recompute the expiration time, which uses `datetime.utcnow() + expire_after`.

When developing a scraping script, I prefer to cache the response for some time in order to avoid making request multiple times when fixing the bugs. So in this case what I prefer to have is an expiration time based on the creation time + expire_after.

**Comment by JWCook** [comment]
In that case, you can use a `datetime` object (instead of a `timedelta` or number of seconds) to give the exact expiration date/time you want.

**Comment by char101** [comment]
But where can I get the creation time of each cached response to compute the new expiration time since different site might have different caching period?

It would be more easier if other than `expire_after` we could pass a function `expire_fn` to inspect the response before it is returned.

**Comment by JWCook** [comment]
I see. If you want to do this on a per-request basis, you can use `CachedSession.cache.save_response()` with the expiration you want. You can get creation time with `CachedResponse.created_at`. Example:

```python
from datetime import timedelta
from requests_cache import CachedSession

session = CachedSession()
response = session.get('https://httpbin.org/get')
if response.from_cache:
    new_expires = response.created_at + timedelta(seconds=300)
    session.cache.save_response(response, expires=new_expires)
```

Or, you could make a custom session class and override `CachedSession.request()`:
```python
class CustomSession(CachedSession):
    def request(self, method: str, url: str, **kwargs):
        response = super().request(method, url, **kwargs)
        if response.from_cache:
            new_expires = response.expires + timedelta(seconds=300)
            self.cache.save_response(response, expires=new_expires)
        return response
```

**Comment by char101** [comment]
Thanks for the example.

What I want is probably something like this

```python
class CustomSession(CachedSession):
    def request(self, method: str, url: str, **kwargs):
        response = super().request(method, url, **kwargs)
        expire_after = kwargs['expire_after']
        if response.from_cache and (time.time() - response.created_at) > expire_after: 
            self.cache.save_response(response, expires=datetime.now())
            response = super().request(method, url, **kwargs)
        return response
```

It seems that it could work with one drawback that any request hook will be called twice.
