### ISSUE TITLE
Random JSONDecodeError Issue

### ISSUE THREAD

**Issue by mdp18** [reclosedev/requests-cache#487]
Hi all, I'm having issues implementing a cache for two requests I make with my app. In the past it ran flawlessly but now I've been getting an Invalid JSON body error each time I call the requests. Both of the requests come back with a 200 response so It has me a little bit confused. 
Traceback below. It looks like cache_keys is having issues normalizing some json body but I'm not entirely sure what json that is. 

```python 
Invalid JSON body:
Traceback (most recent call last):
  File "C:\Users\Max\.virtualenvs\POVGenerator-GUI-WQBjtToE\lib\site-packages\requests_cache\cache_keys.py", line 165, in normalize_json_body
    body = json.loads(decode(original_body))
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by JWCook** [comment]
That's odd, that statement is already inside a try-except block that catches `ValueError`, which `JSONDecodeError` inherits from.

What version of requests-cache are you using? And can you give me example code (or a URL) that reproduces this?

**Comment by mdp18** [comment]
requests-cache-0.9.0
Currently I've isolated it to an api call with a bearer authentication token inside of the header.. I'm not sure if I can provide the code it self though as it has my api-key in it.

**Comment by JWCook** [comment]
Is this exception actually unhandled, or are you just seeing this in the logs?

**Comment by JWCook** [comment]
If you're only seeing this in the logs, then that's just a warning and you can safely ignore it. Mostly likely the server is sending a `Content-Type: application/json` header without actually sending any JSON.

**Comment by mdp18** [comment]
I believe it's handled as the catch ends up returning the original body as stated in the cache_keys.py. Will this have any affect on the program retrieving the cached file? The server is sending ''Content-Type': 'application/json'"

'''json
{'Date': 'Tue, 04 Jan 2022 01:08:46 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Expires': 'Tue, 04 Jan 2022 01:08:45 GMT', 'Cache-Control': 'no-cache, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Pragma': 'no-cache', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '6c8093d92c557c79-LAX', 'Content-Encoding': 'gzip'}'''

**Comment by JWCook** [comment]
> Will this have any affect on the program retrieving the cached file?

No, I think you're safe to ignore that warning.

**Comment by mdp18** [comment]
> > Will this have any affect on the program retrieving the cached file?
> 
> No, I think you're safe to ignore that warning.

Okay. Thank you for your help.

**Comment by JWCook** [comment]
Fyi, this log message will be bumped down to debug level in the next patch release.

**Comment by mdp18** [comment]
Got it thank you for all your help. Very much appreciated.
