### ISSUE TITLE
Possible to chain multiple backends?

### ISSUE THREAD

**Issue by kinghuang** [reclosedev/requests-cache#488]
Is it possible to chain multiple backends together? For example, can I configure a CachedSession with a `filesystem` backend that will in turn check a `redis` backend if it doesn't have a cached response? And, have it cache the response from `redis` locally?

I basically want to have a remote `redis` cache that can be used by multiple requests session, but also an ephemeral `filesystem` cache in between so that repeated requests in the same session don't have to hit Redis over and over again. New cached responses should be stored in the local `filesystem` cache and `redis` cache.

**Comment by JWCook** [comment]
That's not currently possible as a built-in feature, but what you want to do makes sense. I think this could be done with a custom session class that overrides `CachedSession.request()`. Here's a partial outline as an example:

```python
from requests_cache import CachedSession, BackendSpecifier, init_backend


class MultiCachedSession(CachedSession):
    def __init__(
        self,
        cache_name: str = 'http_cache',
        l1_backend: BackendSpecifier = None,
        **kwargs,
    ):
        """Initialize with an additional cache backend"""
        super().__init__(cache_name=cache_name, **kwargs)
        self.l1_cache = init_backend(cache_name, l1_backend, **kwargs)

    def request(self, method: str, url: str, **kwargs):
        """Send a request with 2 cache levels"""
        # TODO: Check if request is already cached in "L1" cache and isn't expired
        # ...
        # Otherwise, use normal behavior with "L2" cache
        super().request(method, url, **kwargs)


# Usage example
session = MultiCachedSession(l1_backend='filesystem', backend='redis')
```


This has a couple potential problems, mainly that some of the logic in `CachedSession.send()` will need to be duplicated. I think issue #394 may make this a bit easier. Once that's done, I'll follow up here with a more complete example.

**Comment by JWCook** [comment]
@kinghuang #394 is done, and the `only_if_cached` option is now available in the latest pre-release build. Here is an example that I think accomplishes what you want:

```python
from requests_cache import CachedSession, BackendSpecifier


class MultiCachedSession(CachedSession):
    def __init__(
        self,
        cache_name: str = 'http_cache',
        backend: BackendSpecifier = None,
        l1_backend: BackendSpecifier = None,
        **kwargs,
    ):
        """Initialize with an additional cache backend"""
        super().__init__(cache_name=cache_name, backend=backend, **kwargs)
        self.l1_session = CachedSession(cache_name, backend=l1_backend, **kwargs)

    def request(self, method: str, url: str, **kwargs):
        """Send a request with 2 cache levels"""
        # Check if request is already in "L1" cache. If missing or expired, it will return a 504 response.
        response = self.l1_session.request(method, url, only_if_cached=True, **kwargs)
        if response.status_code != 504:
            return response

        # Fall back to normal behavior using "L2" cache
        return super().request(method, url, **kwargs)


# Usage example
session = MultiCachedSession(l1_backend='filesystem', backend='redis')
```
