### ISSUE TITLE
normalize_request and url parameter keys without values

### ISSUE THREAD

**Issue by n-a-t-e** [reclosedev/requests-cache#499]
### The problem
requests-cache returns the same cache response for these two URLs, even though they are not the same page:
https://oceanview.pfeg.noaa.gov/erddap/tabledap/erdCalCOFIeggstg.htmlTable?time
https://oceanview.pfeg.noaa.gov/erddap/tabledap/erdCalCOFIeggstg.htmlTable?station

There doesn't seem to be a way to disable the `normalize_request` function, unless I missed something.

### Expected behavior
They should be treated as separate

### Steps to reproduce the behavior
```python
import requests
import requests_cache

requests_cache.install_cache('url_parameter_key_without_value')

res=requests.get('https://oceanview.pfeg.noaa.gov/erddap/tabledap/erdCalCOFIeggstg.csv?time')
print(res.from_cache)

res=requests.get('https://oceanview.pfeg.noaa.gov/erddap/tabledap/erdCalCOFIeggstg.csv?station')
print(res.from_cache)

print('\n'.join(requests_cache.get_cache().urls))
```

### Workarounds
I commented out a call to`normalize_request` in the code for now

### Environment
- requests-cache version: `master`
- Python version: `3.9.2`
- Platform: OSX/Conda

**Comment by JWCook** [comment]
Thanks for reporting this! I'll get that fixed soon.

**Comment by JWCook** [comment]
Done! This will be included in the next patch release.
