### ISSUE TITLE
Behavior during redis connection interruption

### ISSUE THREAD

**Issue by hdonnay** [reclosedev/requests-cache#509]
Hello,

I'm looking into using the Redis cache module, but don't have a good sense of what will happen if the cache get/set operations fail.
I would assume the request would continue as if there were no cache, but don't see this called out in the docs and my python is sufficiently rusty that I can't really tell what would happen just from reading.

Happy to contribute some prose to the documentation if someone could help me understand what the expected behavior is.

**Comment by JWCook** [comment]
Currently, requests-cache doesn't do any backend-specific error handling for you. That's something for which different applications are going to want different behavior, so I'm not sure that's something we would want to add to the library, but I'm open to suggestions.

So for any backend, a connection error will propagate up to your application. For Redis in particular, you can pass [redis-py connection settings](https://redis-py.readthedocs.io/en/stable/connections.html) to change that behavior. For example:
```python
from requests_cache import CachedSession, RedisCache

backend = RedisCache(socket_timeout=5, retry_on_timeout=True)
session = CachedSession(backend=backend)
```

If you're expecting connection interruptions, and want to ignore them and fall back to non-cached requests, you can do something like:
```python
from redis import ConnectionError
from requests import Session
from requests_cache import CachedSession

session = CachedSession(backend='redis')
fallback_session = Session()

try:
    response = session.get('url')
except ConnectionError:
    response = fallback_session.get('url')  # or just requests.get
```

If you're making requests in multiple places and want the same behavior, you could subclass `CachedSession` and put that try-except inside the `request()` method:
```python
from redis import ConnectionError
from requests import Session
from requests_cache import CachedSession

class CustomSession(CachedSession):
    def request(self, *args, **kwargs):
        # Attempt cached request
        try:
            return super().get(*args, **kwargs)
        # If backend is unavailable, fall back to non-cached request
        except ConnectionError:
            return Session.get(self, *args, **kwargs)
```
