### ISSUE TITLE
FTP support

### ISSUE THREAD

**Issue by femtotrader** [reclosedev/requests-cache#57]
Hello Roman,

I wonder if requests-cache could support FTP.
It will be great for https://github.com/pydata/pandas-datareader/pull/145
see https://github.com/pydata/pandas-datareader/issues/143

I noticed this project for FTP support with requests
https://github.com/Lukasa/requests-ftp
https://pypi.python.org/pypi/requests-ftp

Kind regards

**Comment by reclosedev** [comment]
Hi,
In my practice FTP is used for middle/big sized binary files. Not sure that caching it in DB is optimal.
Anyway, If you'll provide PR with ``requests-ftp`` support, I will accept it.

**Comment by femtotrader** [comment]
Hi,

we found that it's directly possible "out of the box"

see this minimal example

```
import requests_ftp
import datetime
requests_ftp.monkeypatch_session()
import requests
import requests_cache
from pandas.io.common import ZipFile
from pandas.compat import BytesIO


# session = requests.Session()

_URL = 'ftp://ftp.sec.gov/edgar/full-index/master.zip'

s = requests_cache.CachedSession(cache_name='cache', backend='sqlite',
                                 expire_after=datetime.timedelta(days=60))
response = s.get(_URL)
content = response.content

content = BytesIO(content)

with ZipFile(content, 'r') as zf:
    index_file = zf.open(zf.namelist()[0]).read().decode()

with open('master.txt', 'w') as fd:
    fd.write(index_file)
```

but that's probably not very efficient.

If you have a better idea...

**Comment by JWCook** [comment]
The filesystem cache proposed here is probably what you want for caching large files from FTP: #30
