### ISSUE TITLE
Make redislite optional

### ISSUE THREAD

**Issue by ldng** [reclosedev/requests-cache#59]
Hi,

would it be possible to make the dependency on redislite optional ?
It be can be difficult to compile on some platforms.

**Comment by reclosedev** [comment]
Hi,

can you please elaborate? Redis is required only if you wan't to use redis storage. Do you wan't to use ``redislite`` instead ``redis``? 
According to https://github.com/yahoo/redislite#example  you could try to use monkeypatch.

I havn't used ``redislite`` before. Interesting porject btw, thank you ;).

**Comment by reclosedev** [comment]
No required info. Closing.
Feel free to reopen.
