### ISSUE TITLE
Take into account content negotiation with GET-requests

### ISSUE THREAD

**Issue by mhermans** [reclosedev/requests-cache#6]
POST-headers are apparently taken into account when caching requests, but not for GET-requests.

In the case of content negotiation with GET-requests, it would be useful if the cache could take into account at least the Accept-header, allowing to case responses in different formats for the same URI.

**Comment by mnowotka** [comment]
+1

    requests.get('some_link', headers={'Accept':'application/json'})
    requests.get('some_link', headers={'Accept':'application/xml'})

Will both return results in json as the second request was taken from cache :(

**Comment by reclosedev** [comment]
Added option to include headers to cache key: ``include_get_headers`` (bool)
By default it's disabled for compatibility with existing code.
See usage example in tests
[test_cache.py#L304-L325](https://github.com/reclosedev/requests-cache/blob/df8d552be8299253f9b2ff6b6e12bb885c4cff61/tests/test_cache.py#L304-L325)

**Comment by JWCook** [comment]
See also: #389, #387
