### ISSUE TITLE
install_cache() with memory backend is not working properly in version 0.9.4

### ISSUE THREAD

**Issue by hlYassine** [reclosedev/requests-cache#617]
### The problem
Memory backend not working as expected.
I installed the cache using:
`requests_cache.install_cache("my_cache", backend="memory", expire_after=200)`

requests calls within 200sec intervall (after the first requests call) all have `from_cache = False` 
when i switched back to persistent backend, it worked as expected.

### Environment
- requests-cache version:  `0.9.4`
- Python version:  `3.8.0`
- Platform:  Windows 10 Entreprise, Version 1909, OS build 18363.2212

**Comment by JWCook** [comment]
Thanks for reporting. I'll look into it.

Meanwhile, it looks like `CachedSession(backend='memory')` still works as expected.
