### ISSUE TITLE
No way to cache only subset of URLs

### ISSUE THREAD

**Issue by QtRoS** [reclosedev/requests-cache#66]
Is there any ability to cache (or do not cache) URLs which match regex?

I am writing Telegram bot which can be used to search for MOOC from multiple sources. I want to cache search requests but do not cache API requests. Can I do this with this library?

**Comment by QtRoS** [comment]
Ok, seems that I can't do monkey-patching on subset of URLs. 
Everything I needed can be implemented with standalone usage of CachedSession. But it was not obvious for new guy in Python like me. So you should add some examples or something like that.

**Comment by reclosedev** [comment]
You could also use [``requests_cache.enabled``](http://requests-cache.readthedocs.io/en/latest/api.html#requests_cache.core.enabled) context manager.

Or custom ``CachedSession`` class. For example

```python
import re
import requests
import requests_cache


class FilteringCachedSession(requests_cache.CachedSession):
    def __init__(self, cache_regexps, *args, **kwargs):
        super(FilteringCachedSession, self).__init__(*args, **kwargs)
        self._cache_regexps = [re.compile(x) if isinstance(x, basestring) else x for x in cache_regexps]


    def _is_cacheable_url(self, url):
        for regexp in self._cache_regexps:
            if regexp.match(url):
                return True
        return False

    def send(self, request, **kwargs):
        try:
            was_disabled = self._is_cache_disabled
            if not self._is_cacheable_url(request.url):
                self._is_cache_disabled = True
            return super(FilteringCachedSession, self).send(request, **kwargs)
        finally:
            self._is_cache_disabled = was_disabled


def main():
    regexps = [".*/get$"]
    session = FilteringCachedSession(regexps)
    for _ in range(2):
        r1 = session.get("http://httpbin.org/get")
        r2 = session.get("http://httpbin.org/ip")
        print(r1.from_cache, r2.from_cache)
```

**Comment by JWCook** [comment]
For reference, URL glob patterns are now supported: https://requests-cache.readthedocs.io/en/stable/user_guide.html#url-patterns
