### ISSUE TITLE
multiprocessing.RLock ?

### ISSUE THREAD

**Issue by chengguangnan** [reclosedev/requests-cache#67]
I see that we are using threading.RLock().

I was spawn requests with joblib multi-process mode and there are duplicated write requests (I think) which produced a locked sqlite database error. 

What's the best way to handle the problem above? Using `multiprocessing.RLock()`?

**Comment by reclosedev** [comment]
I think sqlite is not a good choice for multiprocessing tasks. Not sure if ``multiprocessing.RLock`` will help at all.

**Comment by shrhawk-entertainer** [comment]
@chengguangnan are you able to resolve this ?

**Comment by JWCook** [comment]
For reference, some improvements have been made for multi-threaded and multi-process SQLite access in `0.6`+, which should have addressed most of the "database locked" errors. If anyone has additional concurrency-related problems, please create a new issue.
