### ISSUE TITLE
Streaming responses for file backend fails if not already in the cache

### ISSUE THREAD

**Issue by davidmegginson** [reclosedev/requests-cache#68]
If a remote resource is not already in the cache for the file backend, the following will return no content:

```
response = requests.get('http://ourairports.com/countries/CA/PE/airports.csv', stream=True)
```

Once it's already cached (and not expired), it returns the proper content.  Here's the full test script (on first run, it will print empty content; on second run, within 60 seconds, it will dump the full remote content).

```
import requests, requests_cache

# Use a file backend with 10-second timeout
requests_cache.install_cache(
    '/tmp/test-requests',
    expire_after=60
)

# Get a streaming response, and try reading the raw stream
response = requests.get('http://ourairports.com/countries/CA/PE/airports.csv', stream=True)

# Will be empty if not already in the cache
print(response.raw.read(-1))
```

(Python 3.5.1, requests-cache 0.4.12)

**Comment by davidmegginson** [comment]
Confirmed in Python 2.7.12 as well.

**Comment by reclosedev** [comment]
Thanks! Fixed.

**Comment by davidmegginson** [comment]
Thank you.  Confirmed working in Python 2.7.12 and Python 3.5.2.
