### ISSUE TITLE
Caching (or not caching) redirects causes inconsistencies

### ISSUE THREAD

**Issue by konklone** [reclosedev/requests-cache#70]
I get undesired caching behavior when using `requests-cache` in combination with the `allow_redirects` flag in `requests`. 

I think the issue is two bugs working together:
- Redirect responses are not cached when `allow_redirects` is set to `False`.
- The cache is accessed even when the `allow_redirects` value is a different value from the one that was present when the cached entry was stored. The [unit tests suggest](https://github.com/reclosedev/requests-cache/blob/master/tests/test_cache.py#L259-L277) the library attempts to factor in options to `requests.get()` when caching requests, so I think this is undesired behavior.

Here's an `ipython` recreation showing it in action:

```
In [1]: import requests, requests_cache

In [2]: requests_cache.install_cache("./testing-cache")

In [3]: requests.get("http://www.konklone.com", allow_redirects=False).from_cache
Out[3]: False

In [4]: requests.get("http://www.konklone.com", allow_redirects=False).from_cache
Out[4]: False

In [5]: requests.get("http://www.konklone.com", allow_redirects=False).status_code
Out[5]: 301

In [6]: requests.get("http://www.konklone.com", allow_redirects=True).from_cache
Out[6]: False

In [7]: requests.get("http://www.konklone.com", allow_redirects=True).from_cache
Out[7]: True

In [8]: requests.get("http://www.konklone.com", allow_redirects=True).status_code
Out[8]: 200

In [9]: requests.get("http://www.konklone.com", allow_redirects=False).from_cache
Out[9]: True

In [10]: requests.get("http://www.konklone.com", allow_redirects=False).status_code
Out[10]: 200
```

**Comment by konklone** [comment]
Similarly, the cache is not properly invalidated when the `verify` argument changes. For example, once I've cached a request with `verify=False`, the cached response is used even `verify=True` is sent.

```
In [4]: requests.get("https://expired.badssl.com", verify=True).from_cache
...
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

In [5]: requests.get("https://expired.badssl.com", verify=False).from_cache
Out[5]: False

In [6]: requests.get("https://expired.badssl.com", verify=False).from_cache
Out[6]: True

In [7]: requests.get("https://expired.badssl.com", verify=True).from_cache
Out[7]: True
```

**Comment by JWCook** [comment]
@konklone I see this issue is several years old now, but is something that's still relevant to you? Including `verify` (and any other arguments to `request()`) in the cache key would be easy enough.

For redirects, you can explicitly cache 301 responses by specifying `allowed_codes=(200, 301)` when creating a `CachedSession`, although that may or may not be the behavior you want.

**Comment by konklone** [comment]
It's been a few years now and I don't work on the project that was making use of this anymore, but my past self [said the tool eventually stopped using `requests-cache`](https://github.com/cisagov/pshtt/pull/131) so I guess I don't care about it anymore.

cc @jsf9k, who I think still maintains the upstream tool that spotted this bug, in case I'm wrong and this is still relevant.

**Comment by JWCook** [comment]
Moved the issue with `verify` to #209.

I'm closing this issue now, since the original question was about caching redirects with `allow_redirects=False`, which can be done by specifying 301, 302, and 303 in `allowed_codes`.

**Comment by voltagex** [comment]
This tripped me up

Step 1:
```
session = requests_cache.CachedSession('wallabag_cache')
initial_response = session.get("https://app.wallabag.it/export/all.json")
```

Step 2:
```
session = requests_cache.CachedSession('wallabag_cache')
initial_response = session.get("https://app.wallabag.it/export/all.json", allow_redirects=False)

```

The cache isn't invalidated in Step 2, where I think it should be.
