### ISSUE TITLE
Use url-normalize to normalize requests before creating cache key

### ISSUE THREAD

**Issue by elad661** [reclosedev/requests-cache#80]
I'm having an issue where cache doesn't persist properly. I'm using python3 and the sqlite backend.

if I open the cache sqlite file, the `urls` table is empty, and the `responses` table has 136 items, even though my script only makes 56 requests which don't change across runs.

I think what's happening here is that (since python dicts are not ordered) the order of the request parameters is slightly different each time, which causes the GET parameter order to be different, and hence the cache key to be different too.

**Comment by gregoryfoster** [comment]
+1, I'm seeing and was wondering the same.  I'm using Python 2.7.10 + SQLite 3.14.0.

**Comment by kachan1208** [comment]
Do you think about redirects?

**Comment by llazzaro** [comment]
same here using python 3.
pip freeze output:

```
requests==2.13.0
requests-cache==0.4.13
```

**Comment by elad661** [comment]
https://github.com/reclosedev/requests-cache/blob/master/requests_cache/backends/base.py#L225

It just takes the URL as-is and computes its hash. If the parameters changed orders (which they might, since `requests` uses a dict for the request parameters and python dicts are not ordered), then the hash would be different.

It'd be better to change this to split off the parameters, sort them, and *then* compute the hash, so it'd be consistent across runs.

**Comment by jhermann** [comment]
* https://en.wikipedia.org/wiki/URL_normalization
* https://github.com/niksite/url-normalize

**Comment by JWCook** [comment]
I think this one is still valid. Would someone like to submit a PR to normalize request params when creating cache keys?
