### ISSUE TITLE
Just an observation on remove_expired_responses()

### ISSUE THREAD

**Issue by asierra01** [reclosedev/requests-cache#81]
I use pandas to download stock data from yahoo, I make it expire every 6 hours. When I do on remove_expired_responses() it takes , session_stock.remove_expired_responses  0:01:33.169417, session_stock.remove_expired_responses  0:00:27.785573, sometimes more than 20 secs ? why so slow ? what I am missing.

**Comment by asierra01** [comment]
I upgraded to python 2.7.13 and re-installed requests-cache on a mac, and it seems to be faster now 

cache_russell2k session_stock.remove_expired_responses  0:00:00.000988
get_r2k  0:00:23.415877 files  3664
cache_sp500 session_stocks.remove_expired_responses  0:00:00.000960
get_snp500   0:00:09.189734 files  1009
cache_ETF session_stocks.remove_expired_responses  0:00:00.271775
I don't know why initially was taking 1 min and 33 sec....

**Comment by JWCook** [comment]
For reference, `remove_expired_responses()` performance has been significantly improved as of `0.7`+, and there is more room for improvement noted here: #364
