### ISSUE TITLE
Falling Back to Cache if 404

### ISSUE THREAD

**Issue by psychemedia** [reclosedev/requests-cache#82]
Is there a recognised pattern or method for using the cache if the live page 404s or there is no network connection?

For example, one way might be to try to get the page without the cache, and if that fails, then try to use the cache:

````
try:
    with requests_cache.disabled():
        r=requests.get('http://httpbin.org/ip')
        if r.status_code!= requests.codes.ok:
            raise ValueError()
        #If this is good, add it to the cache somehow?
        #...
except:
    r=requests.get('http://httpbin.org/ip')

print(getattr(r, 'from_cache', False),r.text)
````

**Comment by yakutovicha** [comment]
I have quite a similar question.

We have a repository server that periodically updates the list of available packages. The "users" download this list of packages employing cached `requests.get()`. However, if the repository server gets down, the caching machinery fails with "Failed to establish a new connection" error.

In that case it would be nice to return the cached information first and later update the cache in the background.

Does anyone has an idea how to achieve that?

**Comment by yakutovicha** [comment]
In case someone else has similar issue as mine, here is the solution I came up with:

```
import requests
import requests_cache
from IPython.lib import backgroundjobs as bg

def update_cache():
    """Run this process asynchronously"""
    requests_cache.install_cache(cache_name='apps_meta', backend='sqlite', expire_after=1, old_data_on_error=True) # Make cache expired
    requests.get(registry_url) # Update cache
    requests_cache.install_cache(cache_name='apps_meta', backend='sqlite') # Return to initial setup


requests_cache.install_cache(cache_name='apps_meta', backend='sqlite') # at start getting data from cache
update_cache_background = bg.BackgroundJobFunc(update_cache) # create cache update job
update_cache_background.start() # start cache update in the background

**Comment by JWCook** [comment]
@psychemedia Would a method to manually cache a response, say `CachedSession.cache_response()`, do what you want? And is this something you would like to submit a PR for?

**Comment by JWCook** [comment]
On second thought, a better solution may be to optionally call `request.raise_for_status()` within `CachedSession.send()` so a 404 will raise an exception, and then use the `old_data_on_error` option to return stale cache data if that happens.

**Comment by JWCook** [comment]
Fyi, changes for the first option I mentioned (manually saving a response) are now in the master branch and in pre-release build `0.7.0.dev255`. You can use `CachedSession.cache.save_response(response)` to manually save a response object.

The second option (adding a `raise_for_status` option) will be done in issue #210. I'll close this issue for now, then, unless there's a different way you would prefer to handle 404s.

**Comment by JWCook** [comment]
Changes for this are now in master. I actually ended up including this in the behavior for `old_data_on_error` instead of adding a separate option.
