### ISSUE TITLE
In-memory cache (BaseCache) not thread-safe

### ISSUE THREAD

**Issue by borisdan** [reclosedev/requests-cache#84]
Hi,
I'm using requests-cache to create an in-memory cache, using BaseCache. BaseCache is not thread-safe, as a simultaneous remove_old_entries() and save_response() or delete() might cause the following error:
> RuntimeError: dictionary changed size during iteration

Initially, I've solved this by putting a lock on my code which calls clear() on the cache, and get() and send() on the requests module. However, this problem came back to haunt me once a 3rd party module which also imports and uses requests was introduced. Since I don't want to go hunting every possible inner use of the requests module, I feel that this needs to be solved inside the BaseCache.

**Comment by JWCook** [comment]
Hi @borisdan, I'm not the repo owner, but I have collaborator access via Code Shelter, and I'm trying to blow the dust off this project after being dormant for awhile. I merged your PR #85 ; do you have any other thoughts on improving the thread-safety of `BaseCache` or any of the persistent backends? Any pointers or additional PRs would be appreciated!

**Comment by borisdan** [comment]
Great @JWCook ! Excellent initiative. I don't have any more outstanding items at the moment.
Is there a plan to do a new release soon?

**Comment by JWCook** [comment]
Yes! I'm not sure how soon, which depends on how much help I can get, but I've started putting the most relevant maintenance issues under the [v0.6 milestone](https://github.com/reclosedev/requests-cache/milestone/1).
