### ISSUE TITLE
Add compatibility with requests-mock

### ISSUE THREAD

**Issue by 1kastner** [reclosedev/requests-cache#87]
When I want to test my programm with requests_mocks, the program runs into recursion. A small example can be found at [this gist](https://gist.github.com/1kastner/f25eb7ed5e21fe6c6e97c20e25c8b427).

**Comment by jordansamuels** [comment]
This is an issue for me as well.

**Comment by bachya** [comment]
Me too. For reference, the CacheControl library (a different approach to caching Requests calls) works fine with requests-mock.

**Comment by Demborg** [comment]
Just ran into this myself

**Comment by JWCook** [comment]
It appears that both requests-cache and requests-mock work by patching `requests.Session`. So whichever gets called last will override the other.

It may be possible to combine both by refactoring `CachedSession` to be usable as a Mixin class, and add a function to requests-cache that takes a `Session` object patched by requests-mock and returns a new Session object with the requests-mock mixin added. There might be better solutions, though.

Is this something that anyone would like to submit a PR for?

**Comment by JWCook** [comment]
Since this is the same fundamental issue as #158 (which I am working on now), I'm going to close this issue.

**Comment by JWCook** [comment]
Done. See examples in PR #183.
