### ISSUE TITLE
Check if mongodb backend is working

### ISSUE THREAD

**Issue by c0da** [reclosedev/requests-cache#91]
Hello everyone,

Does anybody know if it's possible to check if Mongodb is responding? If I try to use requests_cache and mongodb is down, it just freezes the request (maybe it should use the standard requests method to grab the content?)

Thanks in advance!

**Comment by JWCook** [comment]
One solution for this would be to set a short timeout on the MongoClient (I think the default is 30s), wrap the connection in a try-except, and then return `None` (e.g., just go on as if the request wasn't cached).

Would someone like to submit a PR for this?

**Comment by JWCook** [comment]
Closing this issue for now, as this isn't likely to get implemented, and just setting a short timeout seems like a better solution.
