### ISSUE TITLE
remove_expired_responses() not imported in __init__.py

### ISSUE THREAD

**Issue by adargu** [reclosedev/requests-cache#93]
Wanted to `remove_expired_responses()` like you wrote in your [Documentation](https://requests-cache.readthedocs.io/en/latest/user_guide.html#expiration), but got the Error:
`AttributeError: 'module' object has no attribute 'remove_expired_responses'`

Because `remove_expired_responses()` is not imported in `__init__.py`

My workaround:
```
from requests_cache import core
core.remove_expired_responses()
```
Checked the sqlite library and I think it's working.

**Comment by mheppner** [comment]
FYI this hasn't been released in a version yet. Can we get a version bump?
