### ISSUE TITLE
Add separate arguments for cache name and cache path for SQLite (DbDict) backend

### ISSUE THREAD

**Issue by Kylotan** [reclosedev/requests-cache#94]
The docs for CachedSession imply I should be able to supply an optional location argument 
https://requests-cache.readthedocs.io/en/latest/api.html#requests_cache.core.CachedSession
https://requests-cache.readthedocs.io/en/latest/api.html#backends-sqlite

However, this raises an exception, because `DbCache.__init__` already has a location argument; passing one through as a keyword argument gives us `TypeError: __init__() got multiple values for keyword argument 'location'`.

Workaround is to just use the intended location as the cache name.

**Comment by robmosca** [comment]
Yep, same problem here. It would be nice to be able to set separately the cache_name and the file location... (even if the cache name is never used elsewhere practically in the code)

**Comment by JWCook** [comment]
It looks like that exception is the result of too many layers of passing kwargs around, for example here: https://github.com/reclosedev/requests-cache/blob/master/requests_cache/backends/__init__.py#L63

I also agree that separate `cache_name` and `cache_path` (or `location`, or whatever) params would be nice. That should be relatively easy. Would you like to submit a PR for it?

**Comment by JWCook** [comment]
@Kylotan @robmosca This has now been fixed. The issue was with passing a positional argument (`cache_name`) to a keyword argument of a different name (`location`). I also renamed this param to `db_path`, since 'location' might be ambiguous.

Example:
```python
from requests_cache import CachedSession
session = CachedSession(db_path='~/my-db.sqlite', backend='sqlite')
```
Or just:
```python
session = CachedSession('~/my-db')
```
