### ISSUE TITLE
Any way to cache response after processing with callback?

### ISSUE THREAD

**Issue by SeanEaster** [reclosedev/requests-cache#98]
I have a slow function I'd like to apply to the response content, then cache the (smaller, compressed) result of this function. Is there a way to  cache callback results, in particular using the memory backend, or any place I might patch to make this possible?

**Comment by JWCook** [comment]
The simplest way to accomplish this may be to just provide a method to manually cache a response, so you can so something like:
```python
session = CachedSession()
with session.cache_disabled():
        response = session.get('http://httpbin.org/ip')
response = postprocess(response)
session.cache_response(response)
```

Similar to #82 . Do you think that would do what you want?

**Comment by JWCook** [comment]
Changes for this are now in master (and in pre-release build `0.7.0.dev255`). You can use `CachedSession.cache.save_response(response)` to manually save a response object.
