### ISSUE TITLE
Detect when a cached response is returned because of an error

### ISSUE THREAD

**Issue by nottrobin** [reclosedev/requests-cache#99]
Currently, we are able to protect against broken requests by showing old cached data if there's an error:

``` python
session = CachedSession(old_data_on_error=True)
response = session.get('http://broken-api.example.com')
```

However, this will simply mask any errors and return the old data. This means there is no way to know if the data is stale because the communication is broken. I think it's rather important in my applications to provide some notification or alert when the API is down.

I propose that `CachedSession` should add a property to the response object to signify if the data is old, e.g.:

``` python
response = session.get('http://broken-api.example.com')
if response.old_data_from_error:
    context.notify = True
```

I'll submit a PR to this effect when I get a chance.

**Comment by JWCook** [comment]
I see this issue is a few years old now, but that's a good point. This should be fairly easy to do.

**Comment by nottrobin** [comment]
Thanks @JWCook. We don't use requests cache in our apps any more, so I don't have a dog in the fight, but I think this would still be valuable for others.

**Comment by JWCook** [comment]
This is now possible with #189 by checking `response.is_expired`.
